//go:build ignore

// Generate the TiDB SQL adapters from the public repository row types.
package main

import (
	"fmt"
	"go/format"
	"os"
	"reflect"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/hatchet-dev/hatchet/pkg/repository"
	"github.com/hatchet-dev/hatchet/pkg/repository/sqlcv1"
	"github.com/jackc/pgx/v5/pgtype"
)

type taskEvent struct {
	sqlcv1.CreateTaskEventsOLAPParams
	ID         int64
	InsertedAt pgtype.Timestamptz
}
type storedPayload struct {
	Inline      []byte
	ExternalKey string
	IndexFile   bool
}
type traceLookup struct {
	Retry int32
	Trace []byte
	Start time.Time
}
type model struct {
	kind, table, name string
	value             any
}
type field struct {
	name, col, typ, arg, path string
	hot                       bool
}

var models = []model{
	{"task", "v1_tasks_olap", "sqlcv1.V1TasksOlap", sqlcv1.V1TasksOlap{}},
	{"dag", "v1_dags_olap", "sqlcv1.V1DagsOlap", sqlcv1.V1DagsOlap{}},
	{"task_event", "v1_task_events_olap", "taskEvent", taskEvent{}},
	{"payload", "v1_payloads_olap", "storedPayload", storedPayload{}},
	{"event", "v1_events_olap", "sqlcv1.V1EventsOlap", sqlcv1.V1EventsOlap{}},
	{"event_trigger", "v1_event_to_run_olap", "repository.EventTriggersFromExternalId", repository.EventTriggersFromExternalId{}},
	{"span", "v1_otel_trace_olap", "repository.OtelSpanRow", repository.OtelSpanRow{}},
	{"trace_lookup", "v1_otel_trace_lookup_olap", "traceLookup", traceLookup{}},
	{"webhook_failure", "v1_incoming_webhook_validation_failures_olap", "repository.CreateIncomingWebhookFailureLogOpts", repository.CreateIncomingWebhookFailureLogOpts{}},
	{"cel_failure", "v1_cel_evaluation_failures_olap", "repository.CELEvaluationFailure", repository.CELEvaluationFailure{}},
}
var capitals = regexp.MustCompile(`([A-Z]+)([A-Z][a-z])`)
var words = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func snake(s string) string {
	return strings.ToLower(words.ReplaceAllString(capitals.ReplaceAllString(s, `${1}_${2}`), `${1}_${2}`))
}
func fields(m model, t reflect.Type, prefix string) []field {
	var out []field
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		path := prefix + f.Name
		if f.Anonymous {
			out = append(out, fields(m, f.Type, path+".")...)
			continue
		}
		col := strings.Split(f.Tag.Get("json"), ",")[0]
		if col == "" {
			col = snake(f.Name)
		}
		if m.kind == "task_event" && f.Name == "InsertedAt" {
			col = "event_inserted_at"
		}
		if m.kind == "event_trigger" && f.Name == "RunID" {
			col = "linked_run_id"
		}
		if m.kind == "payload" && f.Name == "Inline" {
			col = "inline_payload"
		}
		if m.kind == "trace_lookup" {
			col = map[string]string{"Retry": "retry_count", "Trace": "trace_id", "Start": "start_time"}[f.Name]
		}
		typ, arg := "", "v."+path
		switch f.Type {
		case reflect.TypeOf(uuid.UUID{}):
			typ = "BINARY(16) NOT NULL"
			arg = "uuidArg(" + arg + ")"
		case reflect.TypeOf((*uuid.UUID)(nil)):
			typ = "BINARY(16) NULL"
			arg = "optionalUUID(" + arg + ")"
		case reflect.TypeOf(pgtype.Timestamptz{}):
			typ = "DATETIME(6) NULL"
			arg = "stampArg(" + arg + ")"
		case reflect.TypeOf(time.Time{}):
			typ = "DATETIME(6) NOT NULL"
			arg = "dateArg(" + arg + ")"
		case reflect.TypeOf(pgtype.Text{}):
			typ = "LONGTEXT NULL"
			arg = "textArg(" + arg + ")"
		case reflect.TypeOf(pgtype.Int4{}):
			typ = "INT NULL"
			arg = "int4Arg(" + arg + ")"
		case reflect.TypeOf(pgtype.Int8{}):
			typ = "BIGINT NULL"
			arg = "int8Arg(" + arg + ")"
		default:
			switch f.Type.Kind() {
			case reflect.String:
				typ = "LONGTEXT NOT NULL"
				if f.Type.Name() != "string" {
					typ = "VARCHAR(64) NOT NULL"
					arg = "string(" + arg + ")"
				}
			case reflect.Bool:
				typ = "BOOLEAN NOT NULL"
			case reflect.Int32:
				typ = "INT NOT NULL"
			case reflect.Int64:
				typ = "BIGINT NOT NULL"
			case reflect.Slice:
				if f.Type.Elem().Kind() != reflect.Uint8 {
					panic(f.Name)
				}
				typ = "LONGBLOB NULL"
			default:
				panic(f.Type.String())
			}
		}
		hot := (m.kind == "task" || m.kind == "dag") && (col == "readable_status" || col == "latest_retry_count" || col == "latest_worker_id")
		out = append(out, field{f.Name, col, typ, arg, path, hot})
	}
	return out
}
func main() {
	var code, ddl strings.Builder
	code.WriteString("// Code generated by hack/dev/gen-tidb-codec.go; DO NOT EDIT.\npackage tidb\nimport(\"database/sql\";\"encoding/json\";\"fmt\";\"github.com/hatchet-dev/hatchet/pkg/repository\";\"github.com/hatchet-dev/hatchet/pkg/repository/sqlcv1\")\n")
	code.WriteString("type rowCodec struct { table string; columns []string; selectColumns string }\nfunc codecFor(kind string)(rowCodec,error){switch kind{\n")
	for _, m := range models {
		fs := fields(m, reflect.TypeOf(m.value), "")
		cols := []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at"}
		selects := []string{"e.tenant_id", "e.entity_key", "e.external_id", "e.run_id", "e.task_id", "e.inserted_at"}
		for _, f := range fs {
			if !f.hot && !contains(cols, f.col) {
				cols = append(cols, f.col)
			}
			expr := "e.`" + f.col + "`"
			if f.hot {
				expr = "r.`" + f.col + "`"
			}
			selects = append(selects, expr)
		}
		fmt.Fprintf(&code, "case %q:return rowCodec{%q,[]string{%s},%q},nil\n", m.kind, m.table, quoted(cols), strings.Join(selects, ","))
		fmt.Fprintf(&ddl, "CREATE TABLE IF NOT EXISTS %s (\n tenant_id BINARY(16) NOT NULL,\n entity_key VARBINARY(255) NOT NULL,\n external_id BINARY(16) NOT NULL,\n run_id BINARY(16) NOT NULL,\n task_id BIGINT NOT NULL,\n inserted_at DATETIME(6) NOT NULL,\n", m.table)
		seen := []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at"}
		for _, f := range fs {
			if !f.hot && !contains(seen, f.col) {
				fmt.Fprintf(&ddl, " `%s` %s,\n", f.col, f.typ)
				seen = append(seen, f.col)
			}
		}
		ddl.WriteString(" PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),\n UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),\n KEY entity_run (tenant_id,run_id,inserted_at),\n KEY entity_task (tenant_id,task_id,inserted_at),\n KEY entity_time (inserted_at)\n")
		if m.kind == "span" {
			ddl.WriteString(", KEY trace_lookup (tenant_id,trace_id(32),start_time)\n")
		}
		fmt.Fprintln(&ddl, ") DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));")
	}
	code.WriteString("default:return rowCodec{},fmt.Errorf(\"unsupported TiDB entity %q\",kind)}}\n")
	code.WriteString("func encodeColumns(row entity)([]any,error){args:=[]any{uuidArg(row.Tenant),[]byte(row.Key),uuidArg(row.ExternalID),uuidArg(row.RunID),row.TaskID,dateArg(row.InsertedAt)};switch row.Kind{\n")
	for _, m := range models {
		fmt.Fprintf(&code, "case %q:v,err:=decodeEntity[%s](row);if err!=nil{return nil,err};_ = v\n", m.kind, m.name)
		seen := []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at"}
		for _, f := range fields(m, reflect.TypeOf(m.value), "") {
			if !f.hot && !contains(seen, f.col) {
				fmt.Fprintf(&code, "args=append(args,%s)\n", f.arg)
				seen = append(seen, f.col)
			}
		}
	}
	code.WriteString("default:return nil,fmt.Errorf(\"unsupported entity %q\",row.Kind)};return args,nil}\n")
	code.WriteString("func scanEntity(rows *sql.Rows,kind string)(entity,error){e:=entity{Kind:kind};headers:=[]any{&e.Tenant,&e.Key,&e.ExternalID,&e.RunID,&e.TaskID,&e.InsertedAt};switch kind{\n")
	for _, m := range models {
		fmt.Fprintf(&code, "case %q:v:=new(%s);dest:=append(headers", m.kind, m.name)
		for _, f := range fields(m, reflect.TypeOf(m.value), "") {
			fmt.Fprintf(&code, ",&v.%s", f.path)
		}
		code.WriteString(");if err:=rows.Scan(dest...);err!=nil{return e,err};e.Value=v;body,err:=json.Marshal(v);e.Body=string(body);return e,err\n")
	}
	code.WriteString("default:return e,fmt.Errorf(\"unsupported entity %q\",kind)}}\n")
	formatted, err := format.Source([]byte(code.String()))
	if err != nil {
		panic(err)
	}
	if err = os.WriteFile("pkg/repository/tidb/codec_generated.go", formatted, 0644); err != nil {
		panic(err)
	}
	if err = os.MkdirAll("pkg/repository/tidb/migrations/v2", 0755); err != nil {
		panic(err)
	}
	if err = os.WriteFile("pkg/repository/tidb/migrations/v2/001_entities.sql", []byte(ddl.String()), 0644); err != nil {
		panic(err)
	}
}
func contains(items []string, s string) bool {
	for _, v := range items {
		if v == s {
			return true
		}
	}
	return false
}
func quoted(items []string) string {
	var out []string
	for _, v := range items {
		out = append(out, fmt.Sprintf("%q", v))
	}
	return strings.Join(out, ",")
}
