// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.6
// source: sdks/wego/examples/proto/demo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败。
const _ = grpc.SupportPackageIsVersion9

const (
	// UnaryGreeter_SayHello_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	UnaryGreeter_SayHello_FullMethodName = "/wego.example.v1.UnaryGreeter/SayHello"
	// UnaryGreeter_WaitHello_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	UnaryGreeter_WaitHello_FullMethodName = "/wego.example.v1.UnaryGreeter/WaitHello"
	// UnaryGreeter_ChildHello_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	UnaryGreeter_ChildHello_FullMethodName = "/wego.example.v1.UnaryGreeter/ChildHello"
)

// UnaryGreeterClient is the client API for UnaryGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UnaryGreeter 标准 gRPC 业务服务；同一注册可供 Worker 与网络入口执行。
// UnaryGreeterClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnaryGreeterClient interface {
	// SayHello 普通 unary 请求/响应，映射为 StandaloneTask。
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// WaitHello 可配置 durable 等待的 unary 方法。
	WaitHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// ChildHello 使用任务上下文提交子调用的 unary 方法。
	ChildHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

// unaryGreeterClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type unaryGreeterClient struct {
	// cc 标准 gRPC 调用连接；传入 wego Conn 使用任务传输，原生 Conn 使用网络传输。
	cc grpc.ClientConnInterface
}

// NewUnaryGreeterClient 创建生成客户端视图，借用传入的调用连接，不负责关闭该连接。
func NewUnaryGreeterClient(cc grpc.ClientConnInterface) UnaryGreeterClient {
	return &unaryGreeterClient{cc}
}

// SayHello 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *unaryGreeterClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, UnaryGreeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaitHello 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *unaryGreeterClient) WaitHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, UnaryGreeter_WaitHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChildHello 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *unaryGreeterClient) ChildHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, UnaryGreeter_ChildHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryGreeterServer is the server API for UnaryGreeter service.
// All implementations must embed UnimplementedUnaryGreeterServer
// for forward compatibility.
//
// UnaryGreeter 标准 gRPC 业务服务；同一注册可供 Worker 与网络入口执行。
// UnaryGreeterServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnaryGreeterServer interface {
	// SayHello 普通 unary 请求/响应，映射为 StandaloneTask。
	SayHello(context.Context, *Request) (*Reply, error)
	// WaitHello 可配置 durable 等待的 unary 方法。
	WaitHello(context.Context, *Request) (*Reply, error)
	// ChildHello 使用任务上下文提交子调用的 unary 方法。
	ChildHello(context.Context, *Request) (*Reply, error)
	// 私有兼容性标记，保证默认服务实现按值嵌入且可安全调用。
	mustEmbedUnimplementedUnaryGreeterServer()
}

// UnimplementedUnaryGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
// UnimplementedUnaryGreeterServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnimplementedUnaryGreeterServer struct{}

// SayHello 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedUnaryGreeterServer) SayHello(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// WaitHello 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedUnaryGreeterServer) WaitHello(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitHello not implemented")
}

// ChildHello 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedUnaryGreeterServer) ChildHello(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChildHello not implemented")
}

// mustEmbedUnimplementedUnaryGreeterServer 生成器的服务兼容性检查，要求默认实现按值嵌入，避免 nil 嵌入指针导致运行时 panic。
func (UnimplementedUnaryGreeterServer) mustEmbedUnimplementedUnaryGreeterServer() {}

// testEmbeddedByValue 生成器的服务兼容性检查，要求默认实现按值嵌入，避免 nil 嵌入指针导致运行时 panic。
func (UnimplementedUnaryGreeterServer) testEmbeddedByValue() {}

// UnsafeUnaryGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnaryGreeterServer will
// result in compilation errors.
// UnsafeUnaryGreeterServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnsafeUnaryGreeterServer interface {
	// 私有兼容性标记，保证默认服务实现按值嵌入且可安全调用。
	mustEmbedUnimplementedUnaryGreeterServer()
}

// RegisterUnaryGreeterServer 检查默认实现的值嵌入后注册服务，Worker 与网络 Server 均接受此标准注册入口。
func RegisterUnaryGreeterServer(s grpc.ServiceRegistrar, srv UnaryGreeterServer) {
	// If the following call pancis, it indicates UnimplementedUnaryGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	// 注册时检查默认实现的值嵌入，提前发现 nil 指针嵌入，避免首次请求才 panic。
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnaryGreeter_ServiceDesc, srv)
}

// _UnaryGreeter_SayHello_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _UnaryGreeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(UnaryGreeterServer).SayHello(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryGreeter_SayHello_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryGreeterServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _UnaryGreeter_WaitHello_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _UnaryGreeter_WaitHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(UnaryGreeterServer).WaitHello(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryGreeter_WaitHello_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryGreeterServer).WaitHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _UnaryGreeter_ChildHello_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _UnaryGreeter_ChildHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(UnaryGreeterServer).ChildHello(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryGreeter_ChildHello_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryGreeterServer).ChildHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// UnaryGreeter_ServiceDesc is the grpc.ServiceDesc for UnaryGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
// UnaryGreeter_ServiceDesc 服务注册描述，关联完整服务名、方法与流方向，供 grpc.ServiceRegistrar 使用。
var UnaryGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wego.example.v1.UnaryGreeter",
	HandlerType: (*UnaryGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _UnaryGreeter_SayHello_Handler,
		},
		{
			MethodName: "WaitHello",
			Handler:    _UnaryGreeter_WaitHello_Handler,
		},
		{
			MethodName: "ChildHello",
			Handler:    _UnaryGreeter_ChildHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdks/wego/examples/proto/demo.proto",
}

const (
	// Greeter_SayHello_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Greeter_SayHello_FullMethodName = "/wego.example.v1.Greeter/SayHello"
	// Greeter_WaitHello_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Greeter_WaitHello_FullMethodName = "/wego.example.v1.Greeter/WaitHello"
	// Greeter_ChildHello_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Greeter_ChildHello_FullMethodName = "/wego.example.v1.Greeter/ChildHello"
	// Greeter_UploadHellos_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Greeter_UploadHellos_FullMethodName = "/wego.example.v1.Greeter/UploadHellos"
	// Greeter_WatchHellos_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Greeter_WatchHellos_FullMethodName = "/wego.example.v1.Greeter/WatchHellos"
	// Greeter_ChatHellos_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Greeter_ChatHellos_FullMethodName = "/wego.example.v1.Greeter/ChatHellos"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Greeter 标准 gRPC 业务服务；同一注册可供 Worker 与网络入口执行。
// GreeterClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type GreeterClient interface {
	// SayHello 普通 unary 请求/响应，映射为 StandaloneTask。
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// WaitHello 可配置 durable 等待的 unary 方法。
	WaitHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// ChildHello 使用任务上下文提交子调用的 unary 方法。
	ChildHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// UploadHellos client stream：逐条接收 Request，输入 EOF 后返回一个 Reply。
	UploadHellos(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Reply], error)
	// WatchHellos server stream：接收一个 Request，发送 count 条 Reply。
	WatchHellos(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error)
	// ChatHellos bidi stream：每收到一个 Request 即回复 Reply，两个方向独立关闭。
	ChatHellos(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Reply], error)
}

// greeterClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type greeterClient struct {
	// cc 标准 gRPC 调用连接；传入 wego Conn 使用任务传输，原生 Conn 使用网络传输。
	cc grpc.ClientConnInterface
}

// NewGreeterClient 创建生成客户端视图，借用传入的调用连接，不负责关闭该连接。
func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

// SayHello 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *greeterClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaitHello 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *greeterClient) WaitHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Greeter_WaitHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChildHello 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *greeterClient) ChildHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Greeter_ChildHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadHellos 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *greeterClient) UploadHellos(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Reply], error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// stream, err 底层调用连接创建的流，方向由生成的服务描述决定。
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], Greeter_UploadHellos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	// x 带类型参数的标准 gRPC 流视图，委托底层 ClientStream。
	x := &grpc.GenericClientStream[Request, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
// Greeter_UploadHellosClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Greeter_UploadHellosClient = grpc.ClientStreamingClient[Request, Reply]

// WatchHellos 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *greeterClient) WatchHellos(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// stream, err 底层调用连接创建的流，方向由生成的服务描述决定。
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], Greeter_WatchHellos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	// x 带类型参数的标准 gRPC 流视图，委托底层 ClientStream。
	x := &grpc.GenericClientStream[Request, Reply]{ClientStream: stream}
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
// Greeter_WatchHellosClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Greeter_WatchHellosClient = grpc.ServerStreamingClient[Reply]

// ChatHellos 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *greeterClient) ChatHellos(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Reply], error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// stream, err 底层调用连接创建的流，方向由生成的服务描述决定。
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], Greeter_ChatHellos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	// x 带类型参数的标准 gRPC 流视图，委托底层 ClientStream。
	x := &grpc.GenericClientStream[Request, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
// Greeter_ChatHellosClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Greeter_ChatHellosClient = grpc.BidiStreamingClient[Request, Reply]

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility.
//
// Greeter 标准 gRPC 业务服务；同一注册可供 Worker 与网络入口执行。
// GreeterServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type GreeterServer interface {
	// SayHello 普通 unary 请求/响应，映射为 StandaloneTask。
	SayHello(context.Context, *Request) (*Reply, error)
	// WaitHello 可配置 durable 等待的 unary 方法。
	WaitHello(context.Context, *Request) (*Reply, error)
	// ChildHello 使用任务上下文提交子调用的 unary 方法。
	ChildHello(context.Context, *Request) (*Reply, error)
	// UploadHellos client stream：逐条接收 Request，输入 EOF 后返回一个 Reply。
	UploadHellos(grpc.ClientStreamingServer[Request, Reply]) error
	// WatchHellos server stream：接收一个 Request，发送 count 条 Reply。
	WatchHellos(*Request, grpc.ServerStreamingServer[Reply]) error
	// ChatHellos bidi stream：每收到一个 Request 即回复 Reply，两个方向独立关闭。
	ChatHellos(grpc.BidiStreamingServer[Request, Reply]) error
	// 私有兼容性标记，保证默认服务实现按值嵌入且可安全调用。
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
// UnimplementedGreeterServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnimplementedGreeterServer struct{}

// SayHello 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedGreeterServer) SayHello(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// WaitHello 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedGreeterServer) WaitHello(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitHello not implemented")
}

// ChildHello 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedGreeterServer) ChildHello(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChildHello not implemented")
}

// UploadHellos 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedGreeterServer) UploadHellos(grpc.ClientStreamingServer[Request, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method UploadHellos not implemented")
}

// WatchHellos 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedGreeterServer) WatchHellos(*Request, grpc.ServerStreamingServer[Reply]) error {
	return status.Errorf(codes.Unimplemented, "method WatchHellos not implemented")
}

// ChatHellos 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedGreeterServer) ChatHellos(grpc.BidiStreamingServer[Request, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method ChatHellos not implemented")
}

// mustEmbedUnimplementedGreeterServer 生成器的服务兼容性检查，要求默认实现按值嵌入，避免 nil 嵌入指针导致运行时 panic。
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// testEmbeddedByValue 生成器的服务兼容性检查，要求默认实现按值嵌入，避免 nil 嵌入指针导致运行时 panic。
func (UnimplementedGreeterServer) testEmbeddedByValue() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
// UnsafeGreeterServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnsafeGreeterServer interface {
	// 私有兼容性标记，保证默认服务实现按值嵌入且可安全调用。
	mustEmbedUnimplementedGreeterServer()
}

// RegisterGreeterServer 检查默认实现的值嵌入后注册服务，Worker 与网络 Server 均接受此标准注册入口。
func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	// 注册时检查默认实现的值嵌入，提前发现 nil 指针嵌入，避免首次请求才 panic。
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

// _Greeter_SayHello_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_SayHello_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Greeter_WaitHello_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Greeter_WaitHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(GreeterServer).WaitHello(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_WaitHello_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).WaitHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Greeter_ChildHello_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Greeter_ChildHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(GreeterServer).ChildHello(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_ChildHello_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ChildHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Greeter_UploadHellos_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Greeter_UploadHellos_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).UploadHellos(&grpc.GenericServerStream[Request, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
// Greeter_UploadHellosServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Greeter_UploadHellosServer = grpc.ClientStreamingServer[Request, Reply]

// _Greeter_WatchHellos_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Greeter_WatchHellos_Handler(srv interface{}, stream grpc.ServerStream) error {
	// m 当前生成步骤使用的局部值，后续适配逻辑通过它传递请求或结果。
	m := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).WatchHellos(m, &grpc.GenericServerStream[Request, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
// Greeter_WatchHellosServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Greeter_WatchHellosServer = grpc.ServerStreamingServer[Reply]

// _Greeter_ChatHellos_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Greeter_ChatHellos_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ChatHellos(&grpc.GenericServerStream[Request, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
// Greeter_ChatHellosServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Greeter_ChatHellosServer = grpc.BidiStreamingServer[Request, Reply]

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
// Greeter_ServiceDesc 服务注册描述，关联完整服务名、方法与流方向，供 grpc.ServiceRegistrar 使用。
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wego.example.v1.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "WaitHello",
			Handler:    _Greeter_WaitHello_Handler,
		},
		{
			MethodName: "ChildHello",
			Handler:    _Greeter_ChildHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadHellos",
			Handler:       _Greeter_UploadHellos_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchHellos",
			Handler:       _Greeter_WatchHellos_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatHellos",
			Handler:       _Greeter_ChatHellos_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sdks/wego/examples/proto/demo.proto",
}

const (
	// Temporal_Charge_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Charge_FullMethodName = "/wego.example.v1.Temporal/Charge"
	// Temporal_Validate_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Validate_FullMethodName = "/wego.example.v1.Temporal/Validate"
	// Temporal_Fulfill_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Fulfill_FullMethodName = "/wego.example.v1.Temporal/Fulfill"
	// Temporal_Process_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Process_FullMethodName = "/wego.example.v1.Temporal/Process"
	// Temporal_Welcome_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Welcome_FullMethodName = "/wego.example.v1.Temporal/Welcome"
	// Temporal_Followup_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Followup_FullMethodName = "/wego.example.v1.Temporal/Followup"
	// Temporal_Onboard_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Onboard_FullMethodName = "/wego.example.v1.Temporal/Onboard"
	// Temporal_ChargeWithRetries_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_ChargeWithRetries_FullMethodName = "/wego.example.v1.Temporal/ChargeWithRetries"
	// Temporal_Digest_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Digest_FullMethodName = "/wego.example.v1.Temporal/Digest"
	// Temporal_Approval_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Approval_FullMethodName = "/wego.example.v1.Temporal/Approval"
	// Temporal_Item_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Item_FullMethodName = "/wego.example.v1.Temporal/Item"
	// Temporal_ShipItems_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_ShipItems_FullMethodName = "/wego.example.v1.Temporal/ShipItems"
	// Temporal_Report_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_Report_FullMethodName = "/wego.example.v1.Temporal/Report"
	// Temporal_SyncRecords_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_SyncRecords_FullMethodName = "/wego.example.v1.Temporal/SyncRecords"
	// Temporal_CallModel_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_CallModel_FullMethodName = "/wego.example.v1.Temporal/CallModel"
	// Temporal_LoggedCharge_FullMethodName 完整 RPC 方法名常量，客户端 Invoke / NewStream 与服务注册绑定使用同一值。
	Temporal_LoggedCharge_FullMethodName = "/wego.example.v1.Temporal/LoggedCharge"
)

// TemporalClient is the client API for Temporal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Temporal 标准 gRPC 业务服务；同一注册可供 Worker 与网络入口执行。
// TemporalClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type TemporalClient interface {
	// Charge 受控扣款步骤。
	Charge(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Validate 受控输入校验步骤。
	Validate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Fulfill 读取父任务输出后执行受控履约步骤。
	Fulfill(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Process 父子调用组织步骤。
	Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Welcome 受控欢迎消息步骤。
	Welcome(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Followup durable 等待后续事件的步骤。
	Followup(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Onboard 组织欢迎与后续处理的父任务。
	Onboard(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// ChargeWithRetries 注入失败并检查重试计数的扣款步骤。
	ChargeWithRetries(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Digest durable 生成汇总的步骤。
	Digest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Approval 等待匹配审批事件的步骤。
	Approval(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Item 处理一个批量子项的步骤。
	Item(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// ShipItems 批量提交稳定子任务的父步骤。
	ShipItems(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Report 读取可重放时间并返回受控报告。
	Report(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// SyncRecords 同步受控记录集合的步骤。
	SyncRecords(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// CallModel 模拟模型调用的受控业务步骤。
	CallModel(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// LoggedCharge 输出并查询任务日志的扣款步骤。
	LoggedCharge(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

// temporalClient 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type temporalClient struct {
	// cc 标准 gRPC 调用连接；传入 wego Conn 使用任务传输，原生 Conn 使用网络传输。
	cc grpc.ClientConnInterface
}

// NewTemporalClient 创建生成客户端视图，借用传入的调用连接，不负责关闭该连接。
func NewTemporalClient(cc grpc.ClientConnInterface) TemporalClient {
	return &temporalClient{cc}
}

// Charge 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Charge(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Charge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Validate 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Validate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Fulfill 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Fulfill(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Fulfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Process 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Welcome 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Welcome(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Welcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Followup 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Followup(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Followup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Onboard 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Onboard(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Onboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChargeWithRetries 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) ChargeWithRetries(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_ChargeWithRetries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Digest 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Digest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Digest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Approval 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Approval(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Approval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Item 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Item(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Item_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipItems 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) ShipItems(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_ShipItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Report 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) Report(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncRecords 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) SyncRecords(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_SyncRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallModel 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) CallModel(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_CallModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggedCharge 调用对应的生成 RPC 接口，unary 返回业务响应，流方法返回方向匹配的标准流对象。
func (c *temporalClient) LoggedCharge(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	// cOpts 复制调用选项并附加静态方法标记，不修改调用方传入的选项切片。
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := new(Reply)
	// err 当前调用或解码错误，失败时结束当前请求，不返回未填充的响应。
	err := c.cc.Invoke(ctx, Temporal_LoggedCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalServer is the server API for Temporal service.
// All implementations must embed UnimplementedTemporalServer
// for forward compatibility.
//
// Temporal 标准 gRPC 业务服务；同一注册可供 Worker 与网络入口执行。
// TemporalServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type TemporalServer interface {
	// Charge 受控扣款步骤。
	Charge(context.Context, *Request) (*Reply, error)
	// Validate 受控输入校验步骤。
	Validate(context.Context, *Request) (*Reply, error)
	// Fulfill 读取父任务输出后执行受控履约步骤。
	Fulfill(context.Context, *Request) (*Reply, error)
	// Process 父子调用组织步骤。
	Process(context.Context, *Request) (*Reply, error)
	// Welcome 受控欢迎消息步骤。
	Welcome(context.Context, *Request) (*Reply, error)
	// Followup durable 等待后续事件的步骤。
	Followup(context.Context, *Request) (*Reply, error)
	// Onboard 组织欢迎与后续处理的父任务。
	Onboard(context.Context, *Request) (*Reply, error)
	// ChargeWithRetries 注入失败并检查重试计数的扣款步骤。
	ChargeWithRetries(context.Context, *Request) (*Reply, error)
	// Digest durable 生成汇总的步骤。
	Digest(context.Context, *Request) (*Reply, error)
	// Approval 等待匹配审批事件的步骤。
	Approval(context.Context, *Request) (*Reply, error)
	// Item 处理一个批量子项的步骤。
	Item(context.Context, *Request) (*Reply, error)
	// ShipItems 批量提交稳定子任务的父步骤。
	ShipItems(context.Context, *Request) (*Reply, error)
	// Report 读取可重放时间并返回受控报告。
	Report(context.Context, *Request) (*Reply, error)
	// SyncRecords 同步受控记录集合的步骤。
	SyncRecords(context.Context, *Request) (*Reply, error)
	// CallModel 模拟模型调用的受控业务步骤。
	CallModel(context.Context, *Request) (*Reply, error)
	// LoggedCharge 输出并查询任务日志的扣款步骤。
	LoggedCharge(context.Context, *Request) (*Reply, error)
	// 私有兼容性标记，保证默认服务实现按值嵌入且可安全调用。
	mustEmbedUnimplementedTemporalServer()
}

// UnimplementedTemporalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
// UnimplementedTemporalServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnimplementedTemporalServer struct{}

// Charge 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Charge(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charge not implemented")
}

// Validate 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Validate(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

// Fulfill 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Fulfill(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fulfill not implemented")
}

// Process 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Process(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}

// Welcome 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Welcome(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Welcome not implemented")
}

// Followup 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Followup(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Followup not implemented")
}

// Onboard 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Onboard(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Onboard not implemented")
}

// ChargeWithRetries 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) ChargeWithRetries(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChargeWithRetries not implemented")
}

// Digest 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Digest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Digest not implemented")
}

// Approval 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Approval(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Approval not implemented")
}

// Item 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Item(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Item not implemented")
}

// ShipItems 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) ShipItems(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipItems not implemented")
}

// Report 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) Report(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

// SyncRecords 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) SyncRecords(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncRecords not implemented")
}

// CallModel 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) CallModel(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallModel not implemented")
}

// LoggedCharge 默认未实现方法，返回 Unimplemented 状态，业务需覆盖此方法才能成功执行。
func (UnimplementedTemporalServer) LoggedCharge(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoggedCharge not implemented")
}

// mustEmbedUnimplementedTemporalServer 生成器的服务兼容性检查，要求默认实现按值嵌入，避免 nil 嵌入指针导致运行时 panic。
func (UnimplementedTemporalServer) mustEmbedUnimplementedTemporalServer() {}

// testEmbeddedByValue 生成器的服务兼容性检查，要求默认实现按值嵌入，避免 nil 嵌入指针导致运行时 panic。
func (UnimplementedTemporalServer) testEmbeddedByValue() {}

// UnsafeTemporalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemporalServer will
// result in compilation errors.
// UnsafeTemporalServer 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type UnsafeTemporalServer interface {
	// 私有兼容性标记，保证默认服务实现按值嵌入且可安全调用。
	mustEmbedUnimplementedTemporalServer()
}

// RegisterTemporalServer 检查默认实现的值嵌入后注册服务，Worker 与网络 Server 均接受此标准注册入口。
func RegisterTemporalServer(s grpc.ServiceRegistrar, srv TemporalServer) {
	// If the following call pancis, it indicates UnimplementedTemporalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	// 注册时检查默认实现的值嵌入，提前发现 nil 指针嵌入，避免首次请求才 panic。
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Temporal_ServiceDesc, srv)
}

// _Temporal_Charge_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Charge(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Charge_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Charge(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Validate_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Validate(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Validate_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Validate(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Fulfill_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Fulfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Fulfill(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Fulfill_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Fulfill(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Process_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Process(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Process_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Process(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Welcome_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Welcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Welcome(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Welcome_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Welcome(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Followup_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Followup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Followup(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Followup_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Followup(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Onboard_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Onboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Onboard(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Onboard_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Onboard(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_ChargeWithRetries_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_ChargeWithRetries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).ChargeWithRetries(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_ChargeWithRetries_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).ChargeWithRetries(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Digest_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Digest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Digest(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Digest_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Digest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Approval_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Approval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Approval(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Approval_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Approval(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Item_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Item_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Item(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Item_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Item(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_ShipItems_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_ShipItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).ShipItems(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_ShipItems_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).ShipItems(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_Report_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).Report(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_Report_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).Report(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_SyncRecords_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_SyncRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).SyncRecords(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_SyncRecords_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).SyncRecords(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_CallModel_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_CallModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).CallModel(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_CallModel_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).CallModel(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// _Temporal_LoggedCharge_Handler 解码请求并通过可选拦截器调用注册的业务方法，保持标准 unary 或流 handler 约定。
func _Temporal_LoggedCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	// in 准确请求类型的解码目标，避免将错误消息类型传入业务方法。
	in := new(Request)
	// err 保存请求解码或流消息发送的错误，失败时直接结束调用，不把未完成的请求交给业务。
	if err := dec(in); err != nil {
		return nil, err
	}
	// 没有 unary 拦截器时直接调用业务方法；存在拦截器时走下方统一分派。
	if interceptor == nil {
		return srv.(TemporalServer).LoggedCharge(ctx, in)
	}
	// info 拦截器所需的方法身份和服务实例，FullMethod 使用完整路径。
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Temporal_LoggedCharge_FullMethodName,
	}
	// handler 把通用请求参数转换为准确 protobuf 类型后调用业务方法的闭包。
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServer).LoggedCharge(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Temporal_ServiceDesc is the grpc.ServiceDesc for Temporal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
// Temporal_ServiceDesc 服务注册描述，关联完整服务名、方法与流方向，供 grpc.ServiceRegistrar 使用。
var Temporal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wego.example.v1.Temporal",
	HandlerType: (*TemporalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _Temporal_Charge_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Temporal_Validate_Handler,
		},
		{
			MethodName: "Fulfill",
			Handler:    _Temporal_Fulfill_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _Temporal_Process_Handler,
		},
		{
			MethodName: "Welcome",
			Handler:    _Temporal_Welcome_Handler,
		},
		{
			MethodName: "Followup",
			Handler:    _Temporal_Followup_Handler,
		},
		{
			MethodName: "Onboard",
			Handler:    _Temporal_Onboard_Handler,
		},
		{
			MethodName: "ChargeWithRetries",
			Handler:    _Temporal_ChargeWithRetries_Handler,
		},
		{
			MethodName: "Digest",
			Handler:    _Temporal_Digest_Handler,
		},
		{
			MethodName: "Approval",
			Handler:    _Temporal_Approval_Handler,
		},
		{
			MethodName: "Item",
			Handler:    _Temporal_Item_Handler,
		},
		{
			MethodName: "ShipItems",
			Handler:    _Temporal_ShipItems_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _Temporal_Report_Handler,
		},
		{
			MethodName: "SyncRecords",
			Handler:    _Temporal_SyncRecords_Handler,
		},
		{
			MethodName: "CallModel",
			Handler:    _Temporal_CallModel_Handler,
		},
		{
			MethodName: "LoggedCharge",
			Handler:    _Temporal_LoggedCharge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdks/wego/examples/proto/demo.proto",
}
