// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.6
// source: sdks/wego/examples/proto/demo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败。
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败。
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request 示例业务请求；只有显式配置投影的字段才进入 input.routing。
// Request 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Request struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// message 业务文本，例如请求 "hello" 对应处理后的响应文本。
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// group_key 调度分组字段，例如 group-a 与 group-b 独立限制并发；需显式投影。
	GroupKey string `protobuf:"bytes,2,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// account 示例限流或迁移分组键，只使用受控 fixture 值。
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// tier 动态策略等级，例如 basic 用于选择限流额度。
	Tier string `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	// user_id 受控业务对象身份，用于子调用或事件匹配。
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// id 示例输入身份，可投影到 routing.id 计算幂等键。
	Id string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	// correlation_id 事件与等待任务的关联键，例如 correlation-1。
	CorrelationId string `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// count 输入或输出数量，例如请求 3 条 server stream 输出时为 3。
	Count int32 `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	// delay_millis 受控执行延迟，单位毫秒，例如 100 用于制造慢消费者。
	DelayMillis int32 `protobuf:"varint,9,opt,name=delay_millis,json=delayMillis,proto3" json:"delay_millis,omitempty"`
	// fail 是否注入业务失败，true 用于重试与状态验收。
	Fail bool `protobuf:"varint,10,opt,name=fail,proto3" json:"fail,omitempty"`
	// event_key 等待或发布的事件键。
	EventKey string `protobuf:"bytes,11,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	// image_url 受控图片 fixture 地址，载荷变换不依赖外部图片服务。
	ImageUrl string `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// filters 请求的受控图片处理过滤器列表。
	Filters []string `protobuf:"bytes,13,rep,name=filters,proto3" json:"filters,omitempty"`
	// items 待处理项集合，用于验证批量稳定子调用。
	Items []*Item `protobuf:"bytes,14,rep,name=items,proto3" json:"items,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *Request) Reset() {
	*x = Request{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[0]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*Request) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *Request) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[0]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*Request) Descriptor() ([]byte, []int) {
	return file_sdks_wego_examples_proto_demo_proto_rawDescGZIP(), []int{0}
}

// GetMessage 读取 Message；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetMessage() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Message
	}
	return ""
}

// GetGroupKey 读取 GroupKey；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetGroupKey() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.GroupKey
	}
	return ""
}

// GetAccount 读取 Account；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetAccount() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Account
	}
	return ""
}

// GetTier 读取 Tier；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetTier() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Tier
	}
	return ""
}

// GetUserId 读取 UserId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetUserId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetId 读取 Id；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Id
	}
	return ""
}

// GetCorrelationId 读取 CorrelationId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetCorrelationId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// GetCount 读取 Count；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetCount() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Count
	}
	return 0
}

// GetDelayMillis 读取 DelayMillis；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetDelayMillis() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.DelayMillis
	}
	return 0
}

// GetFail 读取 Fail；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetFail() bool {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Fail
	}
	return false
}

// GetEventKey 读取 EventKey；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetEventKey() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.EventKey
	}
	return ""
}

// GetImageUrl 读取 ImageUrl；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetImageUrl() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// GetFilters 读取 Filters；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetFilters() []string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Filters
	}
	return nil
}

// GetItems 读取 Items；nil 接收者返回该字段零值，不创建业务结果。
func (x *Request) GetItems() []*Item {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Items
	}
	return nil
}

// Reply 示例业务响应，包含用于真实验收的运行身份和业务结果。
// Reply 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Reply struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// message 业务文本，例如请求 "hello" 对应处理后的响应文本。
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// run_id 当前工作流 RunID，网络入口没有任务身份。
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// worker_id 当前执行所属 Worker 身份，用于亲和性与粘性断言。
	WorkerId string `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// retry_count 真实重试次数，首次执行为 0。
	RetryCount int32 `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// count 输入或输出数量，例如请求 3 条 server stream 输出时为 3。
	Count int32 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	// child_run_id 子任务运行身份，重放时应复用已有值。
	ChildRunId string `protobuf:"bytes,6,opt,name=child_run_id,json=childRunId,proto3" json:"child_run_id,omitempty"`
	// parent_run_id 父任务运行身份，验证子调用的身份关联。
	ParentRunId string `protobuf:"bytes,7,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	// processed_at durable Now 记录的处理时间，重放保持相应记录值。
	ProcessedAt string `protobuf:"bytes,8,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	// ok 业务处理是否成功，由 handler 而非仅注册结果决定。
	Ok bool `protobuf:"varint,9,opt,name=ok,proto3" json:"ok,omitempty"`
	// processed_url 受控处理结果的对象引用。
	ProcessedUrl string `protobuf:"bytes,10,opt,name=processed_url,json=processedUrl,proto3" json:"processed_url,omitempty"`
	// image_metadata 受控处理结果的尺寸、格式与已应用过滤器。
	ImageMetadata *ImageMetadata `protobuf:"bytes,11,opt,name=image_metadata,json=imageMetadata,proto3" json:"image_metadata,omitempty"`
	// invocation_count durable handler 调用次数，用于观察驱逐及重放。
	InvocationCount int32 `protobuf:"varint,12,opt,name=invocation_count,json=invocationCount,proto3" json:"invocation_count,omitempty"`
	// child_run_ids 批量子任务的稳定运行身份集合。
	ChildRunIds []string `protobuf:"bytes,13,rep,name=child_run_ids,json=childRunIds,proto3" json:"child_run_ids,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *Reply) Reset() {
	*x = Reply{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[1]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*Reply) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *Reply) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[1]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*Reply) Descriptor() ([]byte, []int) {
	return file_sdks_wego_examples_proto_demo_proto_rawDescGZIP(), []int{1}
}

// GetMessage 读取 Message；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetMessage() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Message
	}
	return ""
}

// GetRunId 读取 RunId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetRunId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.RunId
	}
	return ""
}

// GetWorkerId 读取 WorkerId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetWorkerId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// GetRetryCount 读取 RetryCount；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetRetryCount() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// GetCount 读取 Count；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetCount() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Count
	}
	return 0
}

// GetChildRunId 读取 ChildRunId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetChildRunId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ChildRunId
	}
	return ""
}

// GetParentRunId 读取 ParentRunId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetParentRunId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

// GetProcessedAt 读取 ProcessedAt；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetProcessedAt() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

// GetOk 读取 Ok；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetOk() bool {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Ok
	}
	return false
}

// GetProcessedUrl 读取 ProcessedUrl；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetProcessedUrl() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ProcessedUrl
	}
	return ""
}

// GetImageMetadata 读取 ImageMetadata；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetImageMetadata() *ImageMetadata {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ImageMetadata
	}
	return nil
}

// GetInvocationCount 读取 InvocationCount；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetInvocationCount() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.InvocationCount
	}
	return 0
}

// GetChildRunIds 读取 ChildRunIds；nil 接收者返回该字段零值，不创建业务结果。
func (x *Reply) GetChildRunIds() []string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ChildRunIds
	}
	return nil
}

// ImageMetadata 受控图片处理结果，不访问真实外部业务系统。
// ImageMetadata 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type ImageMetadata struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// size 图片 fixture 的字节数。
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// format 图片 fixture 格式。
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// applied_filters 实际执行过的过滤器，供结果断言。
	AppliedFilters []string `protobuf:"bytes,3,rep,name=applied_filters,json=appliedFilters,proto3" json:"applied_filters,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *ImageMetadata) Reset() {
	*x = ImageMetadata{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[2]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *ImageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*ImageMetadata) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *ImageMetadata) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[2]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMetadata.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*ImageMetadata) Descriptor() ([]byte, []int) {
	return file_sdks_wego_examples_proto_demo_proto_rawDescGZIP(), []int{2}
}

// GetSize 读取 Size；nil 接收者返回该字段零值，不创建业务结果。
func (x *ImageMetadata) GetSize() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Size
	}
	return 0
}

// GetFormat 读取 Format；nil 接收者返回该字段零值，不创建业务结果。
func (x *ImageMetadata) GetFormat() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Format
	}
	return ""
}

// GetAppliedFilters 读取 AppliedFilters；nil 接收者返回该字段零值，不创建业务结果。
func (x *ImageMetadata) GetAppliedFilters() []string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.AppliedFilters
	}
	return nil
}

// Item 批量子调用中的单个商品项，例如 product_id="item-1"、quantity=2。
// Item 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Item struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// product_id 受控商品项身份，例如 item-1。
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// quantity 此项数量，例如 2，用于聚合结果核对。
	Quantity int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *Item) Reset() {
	*x = Item{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[3]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*Item) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *Item) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_examples_proto_demo_proto_msgTypes[3]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*Item) Descriptor() ([]byte, []int) {
	return file_sdks_wego_examples_proto_demo_proto_rawDescGZIP(), []int{3}
}

// GetProductId 读取 ProductId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Item) GetProductId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.ProductId
	}
	return ""
}

// GetQuantity 读取 Quantity；nil 接收者返回该字段零值，不创建业务结果。
func (x *Item) GetQuantity() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Quantity
	}
	return 0
}

// File_sdks_wego_examples_proto_demo_proto 完成初始化的文件反射描述，服务绑定通过它解析准确消息类型。
var File_sdks_wego_examples_proto_demo_proto protoreflect.FileDescriptor

// file_sdks_wego_examples_proto_demo_proto_rawDesc 原始 protobuf 文件描述字节，包含字段编号和服务定义，不能按业务数据修改。
const file_sdks_wego_examples_proto_demo_proto_rawDesc = "" +
	"\n" +
	"#sdks/wego/examples/proto/demo.proto\x12\x0fwego.example.v1\"\x8c\x03\n" +
	"\aRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tgroup_key\x18\x02 \x01(\tR\bgroupKey\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x12\x14\n" +
	"\x05count\x18\b \x01(\x05R\x05count\x12!\n" +
	"\fdelay_millis\x18\t \x01(\x05R\vdelayMillis\x12\x12\n" +
	"\x04fail\x18\n" +
	" \x01(\bR\x04fail\x12\x1b\n" +
	"\tevent_key\x18\v \x01(\tR\beventKey\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12\x18\n" +
	"\afilters\x18\r \x03(\tR\afilters\x12+\n" +
	"\x05items\x18\x0e \x03(\v2\x15.wego.example.v1.ItemR\x05items\"\xc0\x03\n" +
	"\x05Reply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12 \n" +
	"\fchild_run_id\x18\x06 \x01(\tR\n" +
	"childRunId\x12\"\n" +
	"\rparent_run_id\x18\a \x01(\tR\vparentRunId\x12!\n" +
	"\fprocessed_at\x18\b \x01(\tR\vprocessedAt\x12\x0e\n" +
	"\x02ok\x18\t \x01(\bR\x02ok\x12#\n" +
	"\rprocessed_url\x18\n" +
	" \x01(\tR\fprocessedUrl\x12E\n" +
	"\x0eimage_metadata\x18\v \x01(\v2\x1e.wego.example.v1.ImageMetadataR\rimageMetadata\x12)\n" +
	"\x10invocation_count\x18\f \x01(\x05R\x0finvocationCount\x12\"\n" +
	"\rchild_run_ids\x18\r \x03(\tR\vchildRunIds\"d\n" +
	"\rImageMetadata\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12'\n" +
	"\x0fapplied_filters\x18\x03 \x03(\tR\x0eappliedFilters\"A\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity2\xcb\x01\n" +
	"\fUnaryGreeter\x12<\n" +
	"\bSayHello\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12=\n" +
	"\tWaitHello\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12>\n" +
	"\n" +
	"ChildHello\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply2\x91\x03\n" +
	"\aGreeter\x12<\n" +
	"\bSayHello\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12=\n" +
	"\tWaitHello\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12>\n" +
	"\n" +
	"ChildHello\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12B\n" +
	"\fUploadHellos\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply(\x01\x12A\n" +
	"\vWatchHellos\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply0\x01\x12B\n" +
	"\n" +
	"ChatHellos\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply(\x010\x012\xee\a\n" +
	"\bTemporal\x12:\n" +
	"\x06Charge\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12<\n" +
	"\bValidate\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12;\n" +
	"\aFulfill\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12;\n" +
	"\aProcess\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12;\n" +
	"\aWelcome\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12<\n" +
	"\bFollowup\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12;\n" +
	"\aOnboard\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12E\n" +
	"\x11ChargeWithRetries\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12:\n" +
	"\x06Digest\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12<\n" +
	"\bApproval\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x128\n" +
	"\x04Item\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12=\n" +
	"\tShipItems\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12:\n" +
	"\x06Report\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12?\n" +
	"\vSyncRecords\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12=\n" +
	"\tCallModel\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.Reply\x12@\n" +
	"\fLoggedCharge\x12\x18.wego.example.v1.Request\x1a\x16.wego.example.v1.ReplyB<Z:github.com/hatchet-dev/hatchet/sdks/wego/examples/proto;pbb\x06proto3"

var (
	// file_sdks_wego_examples_proto_demo_proto_rawDescOnce 描述符压缩的一次性保护，多个 goroutine 读取时只初始化一次。
	file_sdks_wego_examples_proto_demo_proto_rawDescOnce sync.Once
	// file_sdks_wego_examples_proto_demo_proto_rawDescData 按需生成的 gzip 描述符缓存，后续读取复用相同数据。
	file_sdks_wego_examples_proto_demo_proto_rawDescData []byte
)

// file_sdks_wego_examples_proto_demo_proto_rawDescGZIP 在 sync.Once 中压缩并缓存文件描述，重复调用不会重复压缩。
func file_sdks_wego_examples_proto_demo_proto_rawDescGZIP() []byte {
	file_sdks_wego_examples_proto_demo_proto_rawDescOnce.Do(func() {
		// file_sdks_wego_examples_proto_demo_proto_rawDescData 按需生成的 gzip 描述符缓存，后续读取复用相同数据。
		file_sdks_wego_examples_proto_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdks_wego_examples_proto_demo_proto_rawDesc), len(file_sdks_wego_examples_proto_demo_proto_rawDesc)))
	})
	return file_sdks_wego_examples_proto_demo_proto_rawDescData
}

// file_sdks_wego_examples_proto_demo_proto_msgTypes 消息反射类型表，按生成器编号关联 Go 消息与 protobuf 描述。
var file_sdks_wego_examples_proto_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)

// file_sdks_wego_examples_proto_demo_proto_goTypes Go 类型映射表，包含消息和 map entry，占位索引须与依赖表一致。
var file_sdks_wego_examples_proto_demo_proto_goTypes = []any{
	(*Request)(nil),       // 0: wego.example.v1.Request
	(*Reply)(nil),         // 1: wego.example.v1.Reply
	(*ImageMetadata)(nil), // 2: wego.example.v1.ImageMetadata
	(*Item)(nil),          // 3: wego.example.v1.Item
}

// file_sdks_wego_examples_proto_demo_proto_depIdxs 字段与服务的依赖索引表，初始化时连接输入、输出和嵌套消息类型。
var file_sdks_wego_examples_proto_demo_proto_depIdxs = []int32{
	3,  // 0: wego.example.v1.Request.items:type_name -> wego.example.v1.Item
	2,  // 1: wego.example.v1.Reply.image_metadata:type_name -> wego.example.v1.ImageMetadata
	0,  // 2: wego.example.v1.UnaryGreeter.SayHello:input_type -> wego.example.v1.Request
	0,  // 3: wego.example.v1.UnaryGreeter.WaitHello:input_type -> wego.example.v1.Request
	0,  // 4: wego.example.v1.UnaryGreeter.ChildHello:input_type -> wego.example.v1.Request
	0,  // 5: wego.example.v1.Greeter.SayHello:input_type -> wego.example.v1.Request
	0,  // 6: wego.example.v1.Greeter.WaitHello:input_type -> wego.example.v1.Request
	0,  // 7: wego.example.v1.Greeter.ChildHello:input_type -> wego.example.v1.Request
	0,  // 8: wego.example.v1.Greeter.UploadHellos:input_type -> wego.example.v1.Request
	0,  // 9: wego.example.v1.Greeter.WatchHellos:input_type -> wego.example.v1.Request
	0,  // 10: wego.example.v1.Greeter.ChatHellos:input_type -> wego.example.v1.Request
	0,  // 11: wego.example.v1.Temporal.Charge:input_type -> wego.example.v1.Request
	0,  // 12: wego.example.v1.Temporal.Validate:input_type -> wego.example.v1.Request
	0,  // 13: wego.example.v1.Temporal.Fulfill:input_type -> wego.example.v1.Request
	0,  // 14: wego.example.v1.Temporal.Process:input_type -> wego.example.v1.Request
	0,  // 15: wego.example.v1.Temporal.Welcome:input_type -> wego.example.v1.Request
	0,  // 16: wego.example.v1.Temporal.Followup:input_type -> wego.example.v1.Request
	0,  // 17: wego.example.v1.Temporal.Onboard:input_type -> wego.example.v1.Request
	0,  // 18: wego.example.v1.Temporal.ChargeWithRetries:input_type -> wego.example.v1.Request
	0,  // 19: wego.example.v1.Temporal.Digest:input_type -> wego.example.v1.Request
	0,  // 20: wego.example.v1.Temporal.Approval:input_type -> wego.example.v1.Request
	0,  // 21: wego.example.v1.Temporal.Item:input_type -> wego.example.v1.Request
	0,  // 22: wego.example.v1.Temporal.ShipItems:input_type -> wego.example.v1.Request
	0,  // 23: wego.example.v1.Temporal.Report:input_type -> wego.example.v1.Request
	0,  // 24: wego.example.v1.Temporal.SyncRecords:input_type -> wego.example.v1.Request
	0,  // 25: wego.example.v1.Temporal.CallModel:input_type -> wego.example.v1.Request
	0,  // 26: wego.example.v1.Temporal.LoggedCharge:input_type -> wego.example.v1.Request
	1,  // 27: wego.example.v1.UnaryGreeter.SayHello:output_type -> wego.example.v1.Reply
	1,  // 28: wego.example.v1.UnaryGreeter.WaitHello:output_type -> wego.example.v1.Reply
	1,  // 29: wego.example.v1.UnaryGreeter.ChildHello:output_type -> wego.example.v1.Reply
	1,  // 30: wego.example.v1.Greeter.SayHello:output_type -> wego.example.v1.Reply
	1,  // 31: wego.example.v1.Greeter.WaitHello:output_type -> wego.example.v1.Reply
	1,  // 32: wego.example.v1.Greeter.ChildHello:output_type -> wego.example.v1.Reply
	1,  // 33: wego.example.v1.Greeter.UploadHellos:output_type -> wego.example.v1.Reply
	1,  // 34: wego.example.v1.Greeter.WatchHellos:output_type -> wego.example.v1.Reply
	1,  // 35: wego.example.v1.Greeter.ChatHellos:output_type -> wego.example.v1.Reply
	1,  // 36: wego.example.v1.Temporal.Charge:output_type -> wego.example.v1.Reply
	1,  // 37: wego.example.v1.Temporal.Validate:output_type -> wego.example.v1.Reply
	1,  // 38: wego.example.v1.Temporal.Fulfill:output_type -> wego.example.v1.Reply
	1,  // 39: wego.example.v1.Temporal.Process:output_type -> wego.example.v1.Reply
	1,  // 40: wego.example.v1.Temporal.Welcome:output_type -> wego.example.v1.Reply
	1,  // 41: wego.example.v1.Temporal.Followup:output_type -> wego.example.v1.Reply
	1,  // 42: wego.example.v1.Temporal.Onboard:output_type -> wego.example.v1.Reply
	1,  // 43: wego.example.v1.Temporal.ChargeWithRetries:output_type -> wego.example.v1.Reply
	1,  // 44: wego.example.v1.Temporal.Digest:output_type -> wego.example.v1.Reply
	1,  // 45: wego.example.v1.Temporal.Approval:output_type -> wego.example.v1.Reply
	1,  // 46: wego.example.v1.Temporal.Item:output_type -> wego.example.v1.Reply
	1,  // 47: wego.example.v1.Temporal.ShipItems:output_type -> wego.example.v1.Reply
	1,  // 48: wego.example.v1.Temporal.Report:output_type -> wego.example.v1.Reply
	1,  // 49: wego.example.v1.Temporal.SyncRecords:output_type -> wego.example.v1.Reply
	1,  // 50: wego.example.v1.Temporal.CallModel:output_type -> wego.example.v1.Reply
	1,  // 51: wego.example.v1.Temporal.LoggedCharge:output_type -> wego.example.v1.Reply
	27, // [27:52] is the sub-list for method output_type
	2,  // [2:27] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

// init 初始化文件类型描述和依赖关联；已初始化时立即返回，构建后释放临时类型索引。
func init() { file_sdks_wego_examples_proto_demo_proto_init() }

// file_sdks_wego_examples_proto_demo_proto_init 初始化文件类型描述和依赖关联；已初始化时立即返回，构建后释放临时类型索引。
func file_sdks_wego_examples_proto_demo_proto_init() {
	// 文件描述已经完成初始化时直接返回，避免重复构建类型关联。
	if File_sdks_wego_examples_proto_demo_proto != nil {
		return
	}
	// x 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
	type x struct{}
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdks_wego_examples_proto_demo_proto_rawDesc), len(file_sdks_wego_examples_proto_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sdks_wego_examples_proto_demo_proto_goTypes,
		DependencyIndexes: file_sdks_wego_examples_proto_demo_proto_depIdxs,
		MessageInfos:      file_sdks_wego_examples_proto_demo_proto_msgTypes,
	}.Build()
	File_sdks_wego_examples_proto_demo_proto = out.File
	file_sdks_wego_examples_proto_demo_proto_goTypes = nil
	file_sdks_wego_examples_proto_demo_proto_depIdxs = nil
}
