// Code generated by hack/dev/gen-tidb-codec.go; DO NOT EDIT.
package tidb

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"github.com/hatchet-dev/hatchet/pkg/repository"
	"github.com/hatchet-dev/hatchet/pkg/repository/sqlcv1"
)

type rowCodec struct {
	table         string
	columns       []string
	selectColumns string
}

func codecFor(kind string) (rowCodec, error) {
	switch kind {
	case "task":
		return rowCodec{"v1_tasks_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "id", "queue", "action_id", "step_id", "workflow_id", "workflow_version_id", "workflow_run_id", "schedule_timeout", "step_timeout", "priority", "sticky", "desired_worker_id", "display_name", "input", "additional_metadata", "dag_id", "dag_inserted_at", "parent_task_external_id", "is_durable", "idempotency_key"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`tenant_id`,e.`id`,e.`inserted_at`,e.`external_id`,e.`queue`,e.`action_id`,e.`step_id`,e.`workflow_id`,e.`workflow_version_id`,e.`workflow_run_id`,e.`schedule_timeout`,e.`step_timeout`,e.`priority`,e.`sticky`,e.`desired_worker_id`,e.`display_name`,e.`input`,e.`additional_metadata`,r.`readable_status`,r.`latest_retry_count`,r.`latest_worker_id`,e.`dag_id`,e.`dag_inserted_at`,e.`parent_task_external_id`,e.`is_durable`,e.`idempotency_key`"}, nil
	case "dag":
		return rowCodec{"v1_dags_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "id", "display_name", "workflow_id", "workflow_version_id", "input", "additional_metadata", "parent_task_external_id", "total_tasks", "idempotency_key", "is_dag_operator"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`id`,e.`inserted_at`,e.`tenant_id`,e.`external_id`,e.`display_name`,e.`workflow_id`,e.`workflow_version_id`,r.`readable_status`,e.`input`,e.`additional_metadata`,e.`parent_task_external_id`,e.`total_tasks`,e.`idempotency_key`,r.`latest_retry_count`,e.`is_dag_operator`"}, nil
	case "task_event":
		return rowCodec{"v1_task_events_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "task_inserted_at", "event_type", "workflow_id", "event_timestamp", "readable_status", "retry_count", "error_message", "output", "worker_id", "additional__event_data", "additional__event_message", "durable_invocation_count", "id", "event_inserted_at"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`tenant_id`,e.`task_id`,e.`task_inserted_at`,e.`event_type`,e.`workflow_id`,e.`event_timestamp`,e.`readable_status`,e.`retry_count`,e.`error_message`,e.`output`,e.`worker_id`,e.`additional__event_data`,e.`additional__event_message`,e.`external_id`,e.`durable_invocation_count`,e.`id`,e.`event_inserted_at`"}, nil
	case "payload":
		return rowCodec{"v1_payloads_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "inline_payload", "external_key", "index_file"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`inline_payload`,e.`external_key`,e.`index_file`"}, nil
	case "event":
		return rowCodec{"v1_events_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "id", "seen_at", "key", "payload", "additional_metadata", "scope", "triggering_webhook_name"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`tenant_id`,e.`id`,e.`external_id`,e.`seen_at`,e.`key`,e.`payload`,e.`additional_metadata`,e.`scope`,e.`triggering_webhook_name`"}, nil
	case "event_trigger":
		return rowCodec{"v1_event_to_run_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "linked_run_id", "run_inserted_at", "event_external_id", "event_seen_at", "filter_id"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`linked_run_id`,e.`run_inserted_at`,e.`event_external_id`,e.`event_seen_at`,e.`filter_id`"}, nil
	case "span":
		return rowCodec{"v1_otel_trace_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "start_time", "span_name", "trace_id", "span_kind", "service_name", "status_code", "span_id", "parent_span_id", "status_message", "resource_attributes", "span_attributes", "scope_name", "scope_version", "duration_ns", "retry_count"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`start_time`,e.`span_name`,e.`trace_id`,e.`span_kind`,e.`service_name`,e.`status_code`,e.`span_id`,e.`parent_span_id`,e.`status_message`,e.`resource_attributes`,e.`span_attributes`,e.`scope_name`,e.`scope_version`,e.`duration_ns`,e.`retry_count`"}, nil
	case "trace_lookup":
		return rowCodec{"v1_otel_trace_lookup_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "retry_count", "trace_id", "start_time"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`retry_count`,e.`trace_id`,e.`start_time`"}, nil
	case "webhook_failure":
		return rowCodec{"v1_incoming_webhook_validation_failures_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "webhook_name", "error_text"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`webhook_name`,e.`error_text`"}, nil
	case "cel_failure":
		return rowCodec{"v1_cel_evaluation_failures_olap", []string{"tenant_id", "entity_key", "external_id", "run_id", "task_id", "inserted_at", "source", "error_message"}, "e.tenant_id,e.entity_key,e.external_id,e.run_id,e.task_id,e.inserted_at,e.`source`,e.`error_message`"}, nil
	default:
		return rowCodec{}, fmt.Errorf("unsupported TiDB entity %q", kind)
	}
}
func encodeColumns(row entity) ([]any, error) {
	args := []any{uuidArg(row.Tenant), []byte(row.Key), uuidArg(row.ExternalID), uuidArg(row.RunID), row.TaskID, dateArg(row.InsertedAt)}
	switch row.Kind {
	case "task":
		v, err := decodeEntity[sqlcv1.V1TasksOlap](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.ID)
		args = append(args, v.Queue)
		args = append(args, v.ActionID)
		args = append(args, uuidArg(v.StepID))
		args = append(args, uuidArg(v.WorkflowID))
		args = append(args, uuidArg(v.WorkflowVersionID))
		args = append(args, uuidArg(v.WorkflowRunID))
		args = append(args, v.ScheduleTimeout)
		args = append(args, textArg(v.StepTimeout))
		args = append(args, int4Arg(v.Priority))
		args = append(args, string(v.Sticky))
		args = append(args, optionalUUID(v.DesiredWorkerID))
		args = append(args, v.DisplayName)
		args = append(args, v.Input)
		args = append(args, v.AdditionalMetadata)
		args = append(args, int8Arg(v.DagID))
		args = append(args, stampArg(v.DagInsertedAt))
		args = append(args, optionalUUID(v.ParentTaskExternalID))
		args = append(args, v.IsDurable)
		args = append(args, textArg(v.IdempotencyKey))
	case "dag":
		v, err := decodeEntity[sqlcv1.V1DagsOlap](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.ID)
		args = append(args, v.DisplayName)
		args = append(args, uuidArg(v.WorkflowID))
		args = append(args, uuidArg(v.WorkflowVersionID))
		args = append(args, v.Input)
		args = append(args, v.AdditionalMetadata)
		args = append(args, optionalUUID(v.ParentTaskExternalID))
		args = append(args, v.TotalTasks)
		args = append(args, textArg(v.IdempotencyKey))
		args = append(args, v.IsDagOperator)
	case "task_event":
		v, err := decodeEntity[taskEvent](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, stampArg(v.CreateTaskEventsOLAPParams.TaskInsertedAt))
		args = append(args, string(v.CreateTaskEventsOLAPParams.EventType))
		args = append(args, uuidArg(v.CreateTaskEventsOLAPParams.WorkflowID))
		args = append(args, stampArg(v.CreateTaskEventsOLAPParams.EventTimestamp))
		args = append(args, string(v.CreateTaskEventsOLAPParams.ReadableStatus))
		args = append(args, v.CreateTaskEventsOLAPParams.RetryCount)
		args = append(args, textArg(v.CreateTaskEventsOLAPParams.ErrorMessage))
		args = append(args, v.CreateTaskEventsOLAPParams.Output)
		args = append(args, optionalUUID(v.CreateTaskEventsOLAPParams.WorkerID))
		args = append(args, textArg(v.CreateTaskEventsOLAPParams.AdditionalEventData))
		args = append(args, textArg(v.CreateTaskEventsOLAPParams.AdditionalEventMessage))
		args = append(args, v.CreateTaskEventsOLAPParams.DurableInvocationCount)
		args = append(args, v.ID)
		args = append(args, stampArg(v.InsertedAt))
	case "payload":
		v, err := decodeEntity[storedPayload](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.Inline)
		args = append(args, v.ExternalKey)
		args = append(args, v.IndexFile)
	case "event":
		v, err := decodeEntity[sqlcv1.V1EventsOlap](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.ID)
		args = append(args, stampArg(v.SeenAt))
		args = append(args, v.Key)
		args = append(args, v.Payload)
		args = append(args, v.AdditionalMetadata)
		args = append(args, textArg(v.Scope))
		args = append(args, textArg(v.TriggeringWebhookName))
	case "event_trigger":
		v, err := decodeEntity[repository.EventTriggersFromExternalId](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.RunID)
		args = append(args, stampArg(v.RunInsertedAt))
		args = append(args, uuidArg(v.EventExternalId))
		args = append(args, stampArg(v.EventSeenAt))
		args = append(args, optionalUUID(v.FilterId))
	case "span":
		v, err := decodeEntity[repository.OtelSpanRow](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, stampArg(v.StartTime))
		args = append(args, v.SpanName)
		args = append(args, v.TraceID)
		args = append(args, string(v.SpanKind))
		args = append(args, v.ServiceName)
		args = append(args, string(v.StatusCode))
		args = append(args, v.SpanID)
		args = append(args, textArg(v.ParentSpanID))
		args = append(args, textArg(v.StatusMessage))
		args = append(args, v.ResourceAttributes)
		args = append(args, v.SpanAttributes)
		args = append(args, textArg(v.ScopeName))
		args = append(args, textArg(v.ScopeVersion))
		args = append(args, v.DurationNs)
		args = append(args, v.RetryCount)
	case "trace_lookup":
		v, err := decodeEntity[traceLookup](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.Retry)
		args = append(args, v.Trace)
		args = append(args, dateArg(v.Start))
	case "webhook_failure":
		v, err := decodeEntity[repository.CreateIncomingWebhookFailureLogOpts](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, v.WebhookName)
		args = append(args, v.ErrorText)
	case "cel_failure":
		v, err := decodeEntity[repository.CELEvaluationFailure](row)
		if err != nil {
			return nil, err
		}
		_ = v
		args = append(args, string(v.Source))
		args = append(args, v.ErrorMessage)
	default:
		return nil, fmt.Errorf("unsupported entity %q", row.Kind)
	}
	return args, nil
}
func scanEntity(rows *sql.Rows, kind string) (entity, error) {
	e := entity{Kind: kind}
	headers := []any{&e.Tenant, &e.Key, &e.ExternalID, &e.RunID, &e.TaskID, &e.InsertedAt}
	switch kind {
	case "task":
		v := new(sqlcv1.V1TasksOlap)
		dest := append(headers, &v.TenantID, &v.ID, &v.InsertedAt, &v.ExternalID, &v.Queue, &v.ActionID, &v.StepID, &v.WorkflowID, &v.WorkflowVersionID, &v.WorkflowRunID, &v.ScheduleTimeout, &v.StepTimeout, &v.Priority, &v.Sticky, &v.DesiredWorkerID, &v.DisplayName, &v.Input, &v.AdditionalMetadata, &v.ReadableStatus, &v.LatestRetryCount, &v.LatestWorkerID, &v.DagID, &v.DagInsertedAt, &v.ParentTaskExternalID, &v.IsDurable, &v.IdempotencyKey)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "dag":
		v := new(sqlcv1.V1DagsOlap)
		dest := append(headers, &v.ID, &v.InsertedAt, &v.TenantID, &v.ExternalID, &v.DisplayName, &v.WorkflowID, &v.WorkflowVersionID, &v.ReadableStatus, &v.Input, &v.AdditionalMetadata, &v.ParentTaskExternalID, &v.TotalTasks, &v.IdempotencyKey, &v.LatestRetryCount, &v.IsDagOperator)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "task_event":
		v := new(taskEvent)
		dest := append(headers, &v.CreateTaskEventsOLAPParams.TenantID, &v.CreateTaskEventsOLAPParams.TaskID, &v.CreateTaskEventsOLAPParams.TaskInsertedAt, &v.CreateTaskEventsOLAPParams.EventType, &v.CreateTaskEventsOLAPParams.WorkflowID, &v.CreateTaskEventsOLAPParams.EventTimestamp, &v.CreateTaskEventsOLAPParams.ReadableStatus, &v.CreateTaskEventsOLAPParams.RetryCount, &v.CreateTaskEventsOLAPParams.ErrorMessage, &v.CreateTaskEventsOLAPParams.Output, &v.CreateTaskEventsOLAPParams.WorkerID, &v.CreateTaskEventsOLAPParams.AdditionalEventData, &v.CreateTaskEventsOLAPParams.AdditionalEventMessage, &v.CreateTaskEventsOLAPParams.ExternalID, &v.CreateTaskEventsOLAPParams.DurableInvocationCount, &v.ID, &v.InsertedAt)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "payload":
		v := new(storedPayload)
		dest := append(headers, &v.Inline, &v.ExternalKey, &v.IndexFile)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "event":
		v := new(sqlcv1.V1EventsOlap)
		dest := append(headers, &v.TenantID, &v.ID, &v.ExternalID, &v.SeenAt, &v.Key, &v.Payload, &v.AdditionalMetadata, &v.Scope, &v.TriggeringWebhookName)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "event_trigger":
		v := new(repository.EventTriggersFromExternalId)
		dest := append(headers, &v.RunID, &v.RunInsertedAt, &v.EventExternalId, &v.EventSeenAt, &v.FilterId)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "span":
		v := new(repository.OtelSpanRow)
		dest := append(headers, &v.StartTime, &v.SpanName, &v.TraceID, &v.SpanKind, &v.ServiceName, &v.StatusCode, &v.SpanID, &v.ParentSpanID, &v.StatusMessage, &v.ResourceAttributes, &v.SpanAttributes, &v.ScopeName, &v.ScopeVersion, &v.DurationNs, &v.RetryCount)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "trace_lookup":
		v := new(traceLookup)
		dest := append(headers, &v.Retry, &v.Trace, &v.Start)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "webhook_failure":
		v := new(repository.CreateIncomingWebhookFailureLogOpts)
		dest := append(headers, &v.WebhookName, &v.ErrorText)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	case "cel_failure":
		v := new(repository.CELEvaluationFailure)
		dest := append(headers, &v.Source, &v.ErrorMessage)
		if err := rows.Scan(dest...); err != nil {
			return e, err
		}
		e.Value = v
		body, err := json.Marshal(v)
		e.Body = string(body)
		return e, err
	default:
		return e, fmt.Errorf("unsupported entity %q", kind)
	}
}
