CREATE TABLE IF NOT EXISTS v1_tasks_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `id` BIGINT NOT NULL,
 `queue` LONGTEXT NOT NULL,
 `action_id` LONGTEXT NOT NULL,
 `step_id` BINARY(16) NOT NULL,
 `workflow_id` BINARY(16) NOT NULL,
 `workflow_version_id` BINARY(16) NOT NULL,
 `workflow_run_id` BINARY(16) NOT NULL,
 `schedule_timeout` LONGTEXT NOT NULL,
 `step_timeout` LONGTEXT NULL,
 `priority` INT NULL,
 `sticky` VARCHAR(64) NOT NULL,
 `desired_worker_id` BINARY(16) NULL,
 `display_name` LONGTEXT NOT NULL,
 `input` LONGBLOB NULL,
 `additional_metadata` LONGBLOB NULL,
 `dag_id` BIGINT NULL,
 `dag_inserted_at` DATETIME(6) NULL,
 `parent_task_external_id` BINARY(16) NULL,
 `is_durable` BOOLEAN NOT NULL,
 `idempotency_key` LONGTEXT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_dags_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `id` BIGINT NOT NULL,
 `display_name` LONGTEXT NOT NULL,
 `workflow_id` BINARY(16) NOT NULL,
 `workflow_version_id` BINARY(16) NOT NULL,
 `input` LONGBLOB NULL,
 `additional_metadata` LONGBLOB NULL,
 `parent_task_external_id` BINARY(16) NULL,
 `total_tasks` INT NOT NULL,
 `idempotency_key` LONGTEXT NULL,
 `is_dag_operator` BOOLEAN NOT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_task_events_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `task_inserted_at` DATETIME(6) NULL,
 `event_type` VARCHAR(64) NOT NULL,
 `workflow_id` BINARY(16) NOT NULL,
 `event_timestamp` DATETIME(6) NULL,
 `readable_status` VARCHAR(64) NOT NULL,
 `retry_count` INT NOT NULL,
 `error_message` LONGTEXT NULL,
 `output` LONGBLOB NULL,
 `worker_id` BINARY(16) NULL,
 `additional__event_data` LONGTEXT NULL,
 `additional__event_message` LONGTEXT NULL,
 `durable_invocation_count` INT NOT NULL,
 `id` BIGINT NOT NULL,
 `event_inserted_at` DATETIME(6) NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_payloads_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `inline_payload` LONGBLOB NULL,
 `external_key` LONGTEXT NOT NULL,
 `index_file` BOOLEAN NOT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_events_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `id` BIGINT NOT NULL,
 `seen_at` DATETIME(6) NULL,
 `key` LONGTEXT NOT NULL,
 `payload` LONGBLOB NULL,
 `additional_metadata` LONGBLOB NULL,
 `scope` LONGTEXT NULL,
 `triggering_webhook_name` LONGTEXT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_event_to_run_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `linked_run_id` BIGINT NOT NULL,
 `run_inserted_at` DATETIME(6) NULL,
 `event_external_id` BINARY(16) NOT NULL,
 `event_seen_at` DATETIME(6) NULL,
 `filter_id` BINARY(16) NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_otel_trace_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `start_time` DATETIME(6) NULL,
 `span_name` LONGTEXT NOT NULL,
 `trace_id` LONGTEXT NOT NULL,
 `span_kind` VARCHAR(64) NOT NULL,
 `service_name` LONGTEXT NOT NULL,
 `status_code` VARCHAR(64) NOT NULL,
 `span_id` LONGTEXT NOT NULL,
 `parent_span_id` LONGTEXT NULL,
 `status_message` LONGTEXT NULL,
 `resource_attributes` LONGBLOB NULL,
 `span_attributes` LONGBLOB NULL,
 `scope_name` LONGTEXT NULL,
 `scope_version` LONGTEXT NULL,
 `duration_ns` BIGINT NOT NULL,
 `retry_count` INT NOT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
, KEY trace_lookup (tenant_id,trace_id(32),start_time)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_otel_trace_lookup_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `retry_count` INT NOT NULL,
 `trace_id` LONGBLOB NULL,
 `start_time` DATETIME(6) NOT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_incoming_webhook_validation_failures_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `webhook_name` LONGTEXT NOT NULL,
 `error_text` LONGTEXT NOT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_cel_evaluation_failures_olap (
 tenant_id BINARY(16) NOT NULL,
 entity_key VARBINARY(255) NOT NULL,
 external_id BINARY(16) NOT NULL,
 run_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 inserted_at DATETIME(6) NOT NULL,
 `source` VARCHAR(64) NOT NULL,
 `error_message` LONGTEXT NOT NULL,
 PRIMARY KEY (tenant_id,external_id,inserted_at,entity_key),
 UNIQUE KEY entity_identity (tenant_id,entity_key,inserted_at),
 KEY entity_run (tenant_id,run_id,inserted_at),
 KEY entity_task (tenant_id,task_id,inserted_at),
 KEY entity_time (inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
