CREATE TABLE IF NOT EXISTS v1_task_attempts_olap (
 tenant_id BINARY(16) NOT NULL,
 task_id BIGINT NOT NULL,
 task_inserted_at DATETIME(6) NOT NULL,
 run_id BINARY(16) NOT NULL,
 retry_count INT NOT NULL,
 readable_status VARCHAR(16) NOT NULL,
 detail_status VARCHAR(16) NOT NULL,
 detail_status_terminal BOOLEAN NOT NULL,
 detail_status_at DATETIME(6) NOT NULL,
 detail_output_external_id BINARY(16) NULL,
 detail_output_inserted_at DATETIME(6) NULL,
 detail_output_id BIGINT NULL,
 detail_error_message LONGTEXT NULL,
 detail_error_at DATETIME(6) NULL,
 status_priority INT NOT NULL,
 worker_id BINARY(16) NULL,
 event_count BIGINT NOT NULL,
 first_event_id BIGINT NOT NULL,
 last_event_id BIGINT NOT NULL,
 queued_first DATETIME(6) NULL,
 queued_last DATETIME(6) NULL,
 started_first DATETIME(6) NULL,
 started_last DATETIME(6) NULL,
 finished_first DATETIME(6) NULL,
 finished_last DATETIME(6) NULL,
 run_created_first DATETIME(6) NOT NULL,
 run_started_first DATETIME(6) NULL,
 run_finished_last DATETIME(6) NULL,
 error_message LONGTEXT NULL,
 error_event_id BIGINT NULL,
 output_external_id BINARY(16) NULL,
 output_inserted_at DATETIME(6) NULL,
 output_event_timestamp DATETIME(6) NULL,
 run_output_external_id BINARY(16) NULL,
 run_output_inserted_at DATETIME(6) NULL,
 PRIMARY KEY (tenant_id,task_id,task_inserted_at,retry_count),
 KEY attempt_run (tenant_id,run_id,task_inserted_at),
 KEY attempt_retention (task_inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(task_inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
CREATE TABLE IF NOT EXISTS v1_log_line (
 tenant_id BINARY(16) NOT NULL,
 id BIGINT NOT NULL,
 created_at DATETIME(6) NOT NULL,
 task_id BIGINT NOT NULL,
 task_inserted_at DATETIME(6) NOT NULL,
 workflow_id BINARY(16) NULL,
 step_id BINARY(16) NULL,
 retry_count INT NOT NULL,
 level VARCHAR(8) NOT NULL,
 message LONGTEXT NOT NULL,
 metadata LONGBLOB NULL,
 PRIMARY KEY (tenant_id,id,task_inserted_at),
 KEY log_task (tenant_id,task_id,task_inserted_at,retry_count,created_at,id),
 KEY log_time (tenant_id,created_at,id),
 KEY log_workflow (tenant_id,workflow_id,created_at,id),
 KEY log_step (tenant_id,step_id,created_at,id),
 KEY log_retention (task_inserted_at)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE COLUMNS(task_inserted_at) (PARTITION pmax VALUES LESS THAN (MAXVALUE));
