// 流协议只描述传输元数据；业务 payload 仍使用对应业务消息的 protobuf 编码。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.6
// source: sdks/wego/internal/wire/stream.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败。
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败。
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame 是两个方向共用的协议帧，版本、会话身份及方向均须校验。
// 例如 DATA(seq=2) 先于 DATA(seq=1) 到达时先缓存，按 1、2 交付后发送 ACK=2。
// Frame 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Frame struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// version 为 wire 协议版本，当前只接受 3。
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// stream_id 为 START 创建的会话身份，后续帧必须使用同一值。
	StreamId string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// kind 为 PING、READY、OPEN、DATA、ACK、END、CANCEL 或 HEADER。
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// direction 为 input 或 output，ACK 与 DATA 必须匹配对应方向。
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// seq 从 1 开始递增；END 使用 seq 声明最后输入位置，零消息时为 0。
	Seq uint64 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	// ack 为累计消费位置；ACK=3 同时释放序号 1、2、3 的窗口与字节成本。
	Ack uint64 `protobuf:"varint,6,opt,name=ack,proto3" json:"ack,omitempty"`
	// payload 保存业务 protobuf 字节，DATA 单条默认最多 1 MiB。
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// nonce 关联 PING 与 READY，防止旧握手响应错误地完成当前握手。
	Nonce string `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// metadata 保存多值响应头，例如 x-tag 对应 ["a", "b"]。
	Metadata map[string]*Values `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// status 为 google.rpc.Status 的 protobuf 编码，保留 code 和业务 details。
	Status []byte `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *Frame) Reset() {
	*x = Frame{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[0]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*Frame) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *Frame) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[0]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*Frame) Descriptor() ([]byte, []int) {
	return file_sdks_wego_internal_wire_stream_proto_rawDescGZIP(), []int{0}
}

// GetVersion 读取 Version；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetVersion() uint32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Version
	}
	return 0
}

// GetStreamId 读取 StreamId；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetStreamId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.StreamId
	}
	return ""
}

// GetKind 读取 Kind；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetKind() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Kind
	}
	return ""
}

// GetDirection 读取 Direction；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetDirection() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Direction
	}
	return ""
}

// GetSeq 读取 Seq；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetSeq() uint64 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Seq
	}
	return 0
}

// GetAck 读取 Ack；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetAck() uint64 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Ack
	}
	return 0
}

// GetPayload 读取 Payload；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetPayload() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Payload
	}
	return nil
}

// GetNonce 读取 Nonce；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetNonce() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Nonce
	}
	return ""
}

// GetMetadata 读取 Metadata；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetMetadata() map[string]*Values {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetStatus 读取 Status；nil 接收者返回该字段零值，不创建业务结果。
func (x *Frame) GetStatus() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Status
	}
	return nil
}

// Values 保留同名 metadata 的多个值，不能以单个字符串覆盖。
// Values 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type Values struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// values 保存原始字节；token-bin 的 ff00fe 不受 UTF-8 string 限制。
	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *Values) Reset() {
	*x = Values{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[1]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*Values) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *Values) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[1]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*Values) Descriptor() ([]byte, []int) {
	return file_sdks_wego_internal_wire_stream_proto_rawDescGZIP(), []int{1}
}

// GetValues 读取 Values；nil 接收者返回该字段零值，不创建业务结果。
func (x *Values) GetValues() [][]byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Values
	}
	return nil
}

// StreamResult 是会话任务最终结果；输出完整交付且 status=OK 后才向业务返回 EOF。
// StreamResult 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
type StreamResult struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写。
	state protoimpl.MessageState `protogen:"open.v1"`
	// response 为 client stream handler 的单个最终 protobuf 响应。
	Response []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// status 为最终 google.rpc.Status 的编码；非 OK 必须返回错误而不是 EOF。
	Status []byte `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// trailers 为最终响应尾部 metadata，保持多值语义。
	Trailers map[string]*Values `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// last_seq 为最后输出序号；例如值为 3 时缺少输出 2 不能判定成功完成。
	LastSeq uint64 `protobuf:"varint,4,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// headers 为响应头快照，确保延迟订阅或终态读取仍能恢复调用选项。
	Headers map[string]*Values `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// has_response 区分未发送与零字节 protobuf 响应；恰好一个响应时才为 true。
	HasResponse bool `protobuf:"varint,6,opt,name=has_response,json=hasResponse,proto3" json:"has_response,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容。
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数。
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留。
func (x *StreamResult) Reset() {
	*x = StreamResult{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[2]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码。
func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑。
func (*StreamResult) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图。
func (x *StreamResult) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应。
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[2]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用。
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存。
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述。
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_sdks_wego_internal_wire_stream_proto_rawDescGZIP(), []int{2}
}

// GetResponse 读取 Response；nil 接收者返回该字段零值，不创建业务结果。
func (x *StreamResult) GetResponse() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Response
	}
	return nil
}

// GetStatus 读取 Status；nil 接收者返回该字段零值，不创建业务结果。
func (x *StreamResult) GetStatus() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Status
	}
	return nil
}

// GetTrailers 读取 Trailers；nil 接收者返回该字段零值，不创建业务结果。
func (x *StreamResult) GetTrailers() map[string]*Values {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Trailers
	}
	return nil
}

// GetLastSeq 读取 LastSeq；nil 接收者返回该字段零值，不创建业务结果。
func (x *StreamResult) GetLastSeq() uint64 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// GetHeaders 读取 Headers；nil 接收者返回该字段零值，不创建业务结果。
func (x *StreamResult) GetHeaders() map[string]*Values {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.Headers
	}
	return nil
}

// GetHasResponse 读取 HasResponse；nil 接收者返回该字段零值，不创建业务结果。
func (x *StreamResult) GetHasResponse() bool {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问。
	if x != nil {
		return x.HasResponse
	}
	return false
}

// File_sdks_wego_internal_wire_stream_proto 完成初始化的文件反射描述，服务绑定通过它解析准确消息类型。
var File_sdks_wego_internal_wire_stream_proto protoreflect.FileDescriptor

// file_sdks_wego_internal_wire_stream_proto_rawDesc 原始 protobuf 文件描述字节，包含字段编号和服务定义，不能按业务数据修改。
const file_sdks_wego_internal_wire_stream_proto_rawDesc = "" +
	"\n" +
	"$sdks/wego/internal/wire/stream.proto\x12\fwego.wire.v1\"\xee\x02\n" +
	"\x05Frame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03ack\x18\x06 \x01(\x04R\x03ack\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\x12=\n" +
	"\bmetadata\x18\t \x03(\v2!.wego.wire.v1.Frame.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\fR\x06status\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.wego.wire.v1.ValuesR\x05value:\x028\x01\" \n" +
	"\x06Values\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"\xae\x03\n" +
	"\fStreamResult\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\fR\x06status\x12D\n" +
	"\btrailers\x18\x03 \x03(\v2(.wego.wire.v1.StreamResult.TrailersEntryR\btrailers\x12\x19\n" +
	"\blast_seq\x18\x04 \x01(\x04R\alastSeq\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.wego.wire.v1.StreamResult.HeadersEntryR\aheaders\x12!\n" +
	"\fhas_response\x18\x06 \x01(\bR\vhasResponse\x1aQ\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.wego.wire.v1.ValuesR\x05value:\x028\x01\x1aP\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.wego.wire.v1.ValuesR\x05value:\x028\x01B8Z6github.com/hatchet-dev/hatchet/sdks/wego/internal/wireb\x06proto3"

var (
	// file_sdks_wego_internal_wire_stream_proto_rawDescOnce 描述符压缩的一次性保护，多个 goroutine 读取时只初始化一次。
	file_sdks_wego_internal_wire_stream_proto_rawDescOnce sync.Once
	// file_sdks_wego_internal_wire_stream_proto_rawDescData 按需生成的 gzip 描述符缓存，后续读取复用相同数据。
	file_sdks_wego_internal_wire_stream_proto_rawDescData []byte
)

// file_sdks_wego_internal_wire_stream_proto_rawDescGZIP 在 sync.Once 中压缩并缓存文件描述，重复调用不会重复压缩。
func file_sdks_wego_internal_wire_stream_proto_rawDescGZIP() []byte {
	file_sdks_wego_internal_wire_stream_proto_rawDescOnce.Do(func() {
		// file_sdks_wego_internal_wire_stream_proto_rawDescData 按需生成的 gzip 描述符缓存，后续读取复用相同数据。
		file_sdks_wego_internal_wire_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdks_wego_internal_wire_stream_proto_rawDesc), len(file_sdks_wego_internal_wire_stream_proto_rawDesc)))
	})
	return file_sdks_wego_internal_wire_stream_proto_rawDescData
}

// file_sdks_wego_internal_wire_stream_proto_msgTypes 消息反射类型表，按生成器编号关联 Go 消息与 protobuf 描述。
var file_sdks_wego_internal_wire_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)

// file_sdks_wego_internal_wire_stream_proto_goTypes Go 类型映射表，包含消息和 map entry，占位索引须与依赖表一致。
var file_sdks_wego_internal_wire_stream_proto_goTypes = []any{
	(*Frame)(nil),        // 0: wego.wire.v1.Frame
	(*Values)(nil),       // 1: wego.wire.v1.Values
	(*StreamResult)(nil), // 2: wego.wire.v1.StreamResult
	nil,                  // 3: wego.wire.v1.Frame.MetadataEntry
	nil,                  // 4: wego.wire.v1.StreamResult.TrailersEntry
	nil,                  // 5: wego.wire.v1.StreamResult.HeadersEntry
}

// file_sdks_wego_internal_wire_stream_proto_depIdxs 字段与服务的依赖索引表，初始化时连接输入、输出和嵌套消息类型。
var file_sdks_wego_internal_wire_stream_proto_depIdxs = []int32{
	3, // 0: wego.wire.v1.Frame.metadata:type_name -> wego.wire.v1.Frame.MetadataEntry
	4, // 1: wego.wire.v1.StreamResult.trailers:type_name -> wego.wire.v1.StreamResult.TrailersEntry
	5, // 2: wego.wire.v1.StreamResult.headers:type_name -> wego.wire.v1.StreamResult.HeadersEntry
	1, // 3: wego.wire.v1.Frame.MetadataEntry.value:type_name -> wego.wire.v1.Values
	1, // 4: wego.wire.v1.StreamResult.TrailersEntry.value:type_name -> wego.wire.v1.Values
	1, // 5: wego.wire.v1.StreamResult.HeadersEntry.value:type_name -> wego.wire.v1.Values
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

// init 初始化文件类型描述和依赖关联；已初始化时立即返回，构建后释放临时类型索引。
func init() { file_sdks_wego_internal_wire_stream_proto_init() }

// file_sdks_wego_internal_wire_stream_proto_init 初始化文件类型描述和依赖关联；已初始化时立即返回，构建后释放临时类型索引。
func file_sdks_wego_internal_wire_stream_proto_init() {
	// 文件描述已经完成初始化时直接返回，避免重复构建类型关联。
	if File_sdks_wego_internal_wire_stream_proto != nil {
		return
	}
	// x 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准。
	type x struct{}
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方。
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdks_wego_internal_wire_stream_proto_rawDesc), len(file_sdks_wego_internal_wire_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdks_wego_internal_wire_stream_proto_goTypes,
		DependencyIndexes: file_sdks_wego_internal_wire_stream_proto_depIdxs,
		MessageInfos:      file_sdks_wego_internal_wire_stream_proto_msgTypes,
	}.Build()
	File_sdks_wego_internal_wire_stream_proto = out.File
	file_sdks_wego_internal_wire_stream_proto_goTypes = nil
	file_sdks_wego_internal_wire_stream_proto_depIdxs = nil
}
