// 完整 protobuf 协议帧统一经过 codec；业务 payload 使用 ProtoJSON

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.6
// source: sdks/wego/internal/wire/stream.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	// _ 编译期版本兼容断言，生成代码与 protobuf / gRPC 运行时不匹配时直接构建失败
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values 保留同名 metadata 的多个值，不能以单个字符串覆盖
// Values 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准
type Values struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写
	state protoimpl.MessageState `protogen:"open.v1"`
	// values 保存原始字节；token-bin 的 ff00fe 不受 UTF-8 string 限制
	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留
func (x *Values) Reset() {
	*x = Values{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[0]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码
func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑
func (*Values) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图
func (x *Values) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[0]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述
func (*Values) Descriptor() ([]byte, []int) {
	return file_sdks_wego_internal_wire_stream_proto_rawDescGZIP(), []int{0}
}

// GetValues 读取 Values；nil 接收者返回该字段零值，不创建业务结果
func (x *Values) GetValues() [][]byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Values
	}
	return nil
}

// LogFrame 是协议 4 的持久日志帧；完整帧序列化后统一经过 codec
// CLAIM 与 DATA 均包含执行身份，解码成功后才解释代次和输出序号
// LogFrame 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准
type LogFrame struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写
	state protoimpl.MessageState `protogen:"open.v1"`
	// version 固定为 4，不能与会话协议混用
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// kind 为 CLAIM、HEADERS、DATA、ATTEMPT_END、JOIN、EVENT 或 CANCEL
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// task_run_id 是本日志关联的任务身份，事件 topic 可为空
	TaskRunId string `protobuf:"bytes,3,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"`
	// run_id 是管理入口的运行身份，不假定与 task_run_id 相等
	RunId string `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// method 是完整 RPC 方法名，用于恢复身份校验
	Method string `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	// epoch 使用官方 RetryCount，不能由本地计数代替
	Epoch int32 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// writer 是本次物理执行的随机 nonce
	Writer string `protobuf:"bytes,7,opt,name=writer,proto3" json:"writer,omitempty"`
	// worker_key 是通知地址，不参与展示名称
	WorkerKey string `protobuf:"bytes,8,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	// output_seq 是跨代次连续的业务序号；非 DATA 帧可为零
	OutputSeq uint64 `protobuf:"varint,9,opt,name=output_seq,json=outputSeq,proto3" json:"output_seq,omitempty"`
	// payload 保存业务 ProtoJSON 或事件数据，不单独执行第二次 codec
	Payload []byte `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	// metadata 保存多值 headers，沿用二进制 metadata 表示
	Metadata map[string]*Values `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// trailers 保存当前 attempt 的最终尾部 metadata
	Trailers map[string]*Values `protobuf:"bytes,12,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// status 保存 google.rpc.Status 的 protobuf 编码
	Status []byte `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	// frame_id 关联结束清单或启动屏障，发布重试保持相同值
	FrameId string `protobuf:"bytes,14,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// input_digest 检测同一个幂等键是否误用于不同输入
	InputDigest string `protobuf:"bytes,15,opt,name=input_digest,json=inputDigest,proto3" json:"input_digest,omitempty"`
	// expires_at 使用 Unix 纳秒，为事件和内部通知提供有效期
	ExpiresAt int64 `protobuf:"varint,16,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// old_epoch 与 old_writer 限定取消通知的旧执行目标
	OldEpoch int32 `protobuf:"varint,17,opt,name=old_epoch,json=oldEpoch,proto3" json:"old_epoch,omitempty"`
	// old_writer 只取消匹配旧 nonce 的执行，不能取消接管后的新 writer
	OldWriter string `protobuf:"bytes,18,opt,name=old_writer,json=oldWriter,proto3" json:"old_writer,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留
func (x *LogFrame) Reset() {
	*x = LogFrame{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[1]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码
func (x *LogFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑
func (*LogFrame) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图
func (x *LogFrame) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[1]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFrame.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述
func (*LogFrame) Descriptor() ([]byte, []int) {
	return file_sdks_wego_internal_wire_stream_proto_rawDescGZIP(), []int{1}
}

// GetVersion 读取 Version；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetVersion() uint32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Version
	}
	return 0
}

// GetKind 读取 Kind；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetKind() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Kind
	}
	return ""
}

// GetTaskRunId 读取 TaskRunId；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetTaskRunId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

// GetRunId 读取 RunId；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetRunId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.RunId
	}
	return ""
}

// GetMethod 读取 Method；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetMethod() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Method
	}
	return ""
}

// GetEpoch 读取 Epoch；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetEpoch() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Epoch
	}
	return 0
}

// GetWriter 读取 Writer；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetWriter() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Writer
	}
	return ""
}

// GetWorkerKey 读取 WorkerKey；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetWorkerKey() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

// GetOutputSeq 读取 OutputSeq；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetOutputSeq() uint64 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.OutputSeq
	}
	return 0
}

// GetPayload 读取 Payload；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetPayload() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Payload
	}
	return nil
}

// GetMetadata 读取 Metadata；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetMetadata() map[string]*Values {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetTrailers 读取 Trailers；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetTrailers() map[string]*Values {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Trailers
	}
	return nil
}

// GetStatus 读取 Status；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetStatus() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Status
	}
	return nil
}

// GetFrameId 读取 FrameId；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetFrameId() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.FrameId
	}
	return ""
}

// GetInputDigest 读取 InputDigest；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetInputDigest() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.InputDigest
	}
	return ""
}

// GetExpiresAt 读取 ExpiresAt；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetExpiresAt() int64 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// GetOldEpoch 读取 OldEpoch；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetOldEpoch() int32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.OldEpoch
	}
	return 0
}

// GetOldWriter 读取 OldWriter；nil 接收者返回该字段零值，不创建业务结果
func (x *LogFrame) GetOldWriter() string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.OldWriter
	}
	return ""
}

// EncodedLogFrame 为 codec 解码提供引导信息，不暴露内部执行字段
// EncodedLogFrame 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准
type EncodedLogFrame struct {
	// state protobuf 运行时消息状态，关联当前实例的反射描述；业务不直接读写
	state protoimpl.MessageState `protogen:"open.v1"`
	// format_version 标识此引导封装的格式，目前为 1
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// codec_ids 按 Encode 顺序保存稳定版本标识，接收方必须有相同解码链
	CodecIds []string `protobuf:"bytes,2,rep,name=codec_ids,json=codecIds,proto3" json:"codec_ids,omitempty"`
	// payload 为整帧的 codec 输出，允许是密文或对象引用
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// unknownFields 保留当前版本不认识的字段，重新编码时保持协议前向兼容
	unknownFields protoimpl.UnknownFields
	// sizeCache protobuf 编码大小缓存，由运行时维护，不表示业务消息条数
	sizeCache protoimpl.SizeCache
}

// Reset 清空消息字段并重新关联运行时描述，已保存业务值不再保留
func (x *EncodedLogFrame) Reset() {
	*x = EncodedLogFrame{}
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[2]
	// ms 当前接收者的消息状态缓存，存入描述后反射读取复用
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 生成 protobuf 文本表示，仅用于诊断，不作为任务传输编码
func (x *EncodedLogFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 实现 protobuf 消息标记接口，方法本身不执行业务逻辑
func (*EncodedLogFrame) ProtoMessage() {}

// ProtoReflect 返回消息反射视图，首次读取缓存描述后复用；nil 消息返回类型级反射视图
func (x *EncodedLogFrame) ProtoReflect() protoreflect.Message {
	// mi 当前消息的运行时类型描述，索引与 .proto 消息顺序对应
	mi := &file_sdks_wego_internal_wire_stream_proto_msgTypes[2]
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		// ms 当前接收者的消息状态缓存，存入描述后反射读取复用
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		// 消息状态尚未关联描述时填入当前类型信息，后续反射读取复用此缓存
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedLogFrame.ProtoReflect.Descriptor instead.
// Descriptor 返回压缩文件描述及消息索引；业务新代码使用 ProtoReflect 获取描述
func (*EncodedLogFrame) Descriptor() ([]byte, []int) {
	return file_sdks_wego_internal_wire_stream_proto_rawDescGZIP(), []int{2}
}

// GetFormatVersion 读取 FormatVersion；nil 接收者返回该字段零值，不创建业务结果
func (x *EncodedLogFrame) GetFormatVersion() uint32 {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

// GetCodecIds 读取 CodecIds；nil 接收者返回该字段零值，不创建业务结果
func (x *EncodedLogFrame) GetCodecIds() []string {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.CodecIds
	}
	return nil
}

// GetPayload 读取 Payload；nil 接收者返回该字段零值，不创建业务结果
func (x *EncodedLogFrame) GetPayload() []byte {
	// 非 nil 接收者读取实例状态；nil 路径返回字段零值或类型级描述，避免空指针访问
	if x != nil {
		return x.Payload
	}
	return nil
}

// File_sdks_wego_internal_wire_stream_proto 完成初始化的文件反射描述，服务绑定通过它解析准确消息类型
var File_sdks_wego_internal_wire_stream_proto protoreflect.FileDescriptor

// file_sdks_wego_internal_wire_stream_proto_rawDesc 原始 protobuf 文件描述字节，包含字段编号和服务定义，不能按业务数据修改
const file_sdks_wego_internal_wire_stream_proto_rawDesc = "" +
	"\n" +
	"$sdks/wego/internal/wire/stream.proto\x12\fwego.wire.v1\" \n" +
	"\x06Values\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"\xe8\x05\n" +
	"\bLogFrame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1e\n" +
	"\vtask_run_id\x18\x03 \x01(\tR\ttaskRunId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x05R\x05epoch\x12\x16\n" +
	"\x06writer\x18\a \x01(\tR\x06writer\x12\x1d\n" +
	"\n" +
	"worker_key\x18\b \x01(\tR\tworkerKey\x12\x1d\n" +
	"\n" +
	"output_seq\x18\t \x01(\x04R\toutputSeq\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x12@\n" +
	"\bmetadata\x18\v \x03(\v2$.wego.wire.v1.LogFrame.MetadataEntryR\bmetadata\x12@\n" +
	"\btrailers\x18\f \x03(\v2$.wego.wire.v1.LogFrame.TrailersEntryR\btrailers\x12\x16\n" +
	"\x06status\x18\r \x01(\fR\x06status\x12\x19\n" +
	"\bframe_id\x18\x0e \x01(\tR\aframeId\x12!\n" +
	"\finput_digest\x18\x0f \x01(\tR\vinputDigest\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x10 \x01(\x03R\texpiresAt\x12\x1b\n" +
	"\told_epoch\x18\x11 \x01(\x05R\boldEpoch\x12\x1d\n" +
	"\n" +
	"old_writer\x18\x12 \x01(\tR\toldWriter\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.wego.wire.v1.ValuesR\x05value:\x028\x01\x1aQ\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.wego.wire.v1.ValuesR\x05value:\x028\x01\"o\n" +
	"\x0fEncodedLogFrame\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1b\n" +
	"\tcodec_ids\x18\x02 \x03(\tR\bcodecIds\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB8Z6github.com/hatchet-dev/hatchet/sdks/wego/internal/wireb\x06proto3"

var (
	// file_sdks_wego_internal_wire_stream_proto_rawDescOnce 描述符压缩的一次性保护，多个 goroutine 读取时只初始化一次
	file_sdks_wego_internal_wire_stream_proto_rawDescOnce sync.Once
	// file_sdks_wego_internal_wire_stream_proto_rawDescData 按需生成的 gzip 描述符缓存，后续读取复用相同数据
	file_sdks_wego_internal_wire_stream_proto_rawDescData []byte
)

// file_sdks_wego_internal_wire_stream_proto_rawDescGZIP 在 sync.Once 中压缩并缓存文件描述，重复调用不会重复压缩
func file_sdks_wego_internal_wire_stream_proto_rawDescGZIP() []byte {
	file_sdks_wego_internal_wire_stream_proto_rawDescOnce.Do(func() {
		// file_sdks_wego_internal_wire_stream_proto_rawDescData 按需生成的 gzip 描述符缓存，后续读取复用相同数据
		file_sdks_wego_internal_wire_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdks_wego_internal_wire_stream_proto_rawDesc), len(file_sdks_wego_internal_wire_stream_proto_rawDesc)))
	})
	return file_sdks_wego_internal_wire_stream_proto_rawDescData
}

// file_sdks_wego_internal_wire_stream_proto_msgTypes 消息反射类型表，按生成器编号关联 Go 消息与 protobuf 描述
var file_sdks_wego_internal_wire_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)

// file_sdks_wego_internal_wire_stream_proto_goTypes Go 类型映射表，包含消息和 map entry，占位索引须与依赖表一致
var file_sdks_wego_internal_wire_stream_proto_goTypes = []any{
	(*Values)(nil),          // 0: wego.wire.v1.Values
	(*LogFrame)(nil),        // 1: wego.wire.v1.LogFrame
	(*EncodedLogFrame)(nil), // 2: wego.wire.v1.EncodedLogFrame
	nil,                     // 3: wego.wire.v1.LogFrame.MetadataEntry
	nil,                     // 4: wego.wire.v1.LogFrame.TrailersEntry
}

// file_sdks_wego_internal_wire_stream_proto_depIdxs 字段与服务的依赖索引表，初始化时连接输入、输出和嵌套消息类型
var file_sdks_wego_internal_wire_stream_proto_depIdxs = []int32{
	3, // 0: wego.wire.v1.LogFrame.metadata:type_name -> wego.wire.v1.LogFrame.MetadataEntry
	4, // 1: wego.wire.v1.LogFrame.trailers:type_name -> wego.wire.v1.LogFrame.TrailersEntry
	0, // 2: wego.wire.v1.LogFrame.MetadataEntry.value:type_name -> wego.wire.v1.Values
	0, // 3: wego.wire.v1.LogFrame.TrailersEntry.value:type_name -> wego.wire.v1.Values
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

// init 初始化文件类型描述和依赖关联；已初始化时立即返回，构建后释放临时类型索引
func init() { file_sdks_wego_internal_wire_stream_proto_init() }

// file_sdks_wego_internal_wire_stream_proto_init 初始化文件类型描述和依赖关联；已初始化时立即返回，构建后释放临时类型索引
func file_sdks_wego_internal_wire_stream_proto_init() {
	// 文件描述已经完成初始化时直接返回，避免重复构建类型关联
	if File_sdks_wego_internal_wire_stream_proto != nil {
		return
	}
	// x 生成的消息、调用接口或服务适配类型；业务语义以 .proto 的中文说明为准
	type x struct{}
	// out 待填充的业务响应或文件描述构建结果，成功后才返回调用方
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdks_wego_internal_wire_stream_proto_rawDesc), len(file_sdks_wego_internal_wire_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdks_wego_internal_wire_stream_proto_goTypes,
		DependencyIndexes: file_sdks_wego_internal_wire_stream_proto_depIdxs,
		MessageInfos:      file_sdks_wego_internal_wire_stream_proto_msgTypes,
	}.Build()
	File_sdks_wego_internal_wire_stream_proto = out.File
	file_sdks_wego_internal_wire_stream_proto_goTypes = nil
	file_sdks_wego_internal_wire_stream_proto_depIdxs = nil
}
